In [1]:
%%latex
\tableofcontents

# Explanation

This second piece of the code gives us guidance in how to bin each of the categorical features into fewer categories.  Binary classification algorithms generally work best with fewer than ten categories per feature, but some of our features have hundreds of unique values.

## Binning by Human Understanding of Meaning of Codes:  HOSPITAL

Some of the features, like HOSPITAL, we can bin by looking at what each value signifies and putting them together using human understanding of what the codes signify.  We are only interested in whether the crash person went to the hospital; we do not really care how the person got to the hospital, but the CRSS codes differentiate six ways a person might have gone to the hospital and two ways the information can be unknown.  We will bin CRSS codes 1-6 together as "Yes" and codes 8-9 as 'Unknown,' to be imputed later.

| CRSS Attribute Code | Meaning | Our Bin |
|---|---|---|
| 0  | Not Transported for Treatment  | 0 |
| 1  | EMS Air  | 1 |
| 2  | Law Enforcement  | 1 |
| 3  | EMS Unknown Mode  | 1 |
| 4  | Transported Unknown Source  | 1 |
| 5  | EMS Ground  | 1 |
| 6  | Other  | 1 |
| 8  | Not Reported  | 'Unknown' |
| 9  | Reported as Unknown  | 'Unknown' |

## Binning of Ordered Codes:  HOUR

The crash hours are discrete but ordered.  When binning "similar" times together, we look for "similar" in terms of the likelihood that, at that time of day, a crash person will go to the hospital.  In the table below, crashes at midnight (HOUR = 0) account for 1.5% of crash persons, and 23% of those crash persons went to the hospital.  We see a significant drop between 4 and 7 am in the likelihood that a crash person will go to the hospital, about a 4% drop each hour.  The percentage of crash person going to the hospital stays about the same until 6pm, when it starts to rise again.  Where exactly to cut the bins is a somewhat arbitrary decision.

| HOUR | % of Crash Persons | % to Hospital | Our Bin | Meaning |
|---|---|---|---|---|
| 0 | 1.344 | 23.0705 | 6 | Late Night |
| 1 | 1.0665 | 26.5419 | 6 | Late Night |
| 2 | 0.9483 | 26.6044 | 6 | Late Night |
| 3 | 0.7306 | 26.8372 | 6 | Late Night |
| 4 | 0.7089 | 25.6741 | 6 | Late Night |
| 5 | 1.1962 | 21.2548 | 0 | Early Morning |
| 6 | 2.4013 | 17.1788 | 0 | Early Morning |
| 7 | 4.6948 | 13.1665 | 1 | Morning |
| 8 | 4.5183 | 13.3792 | 1 | Morning |
| 9 | 3.8258 | 14.3828 | 1 | Morning |
| 10 | 4.079 | 14.8444 | 1 | Morning |
| 11 | 5.0904 | 14.1232 | 2 | Mid-Day |
| 12 | 6.2797 | 13.4761 | 2 | Mid-Day |
| 13 | 6.2852 | 14.0212 | 2 | Mid-Day |
| 14 | 7.0741 | 14.1841 | 2 | Mid-Day |
| 15 | 8.6077 | 12.9617 | 3 | Rush Hour |
| 16 | 8.6935 | 13.3526 | 3 | Rush Hour |
| 17 | 9.3121 | 12.6166 | 3 | Rush Hour |
| 18 | 7.0147 | 14.0458 | 4 | Early Evening |
| 19 | 4.8031 | 16.2731 | 4 | Early Evening |
| 20 | 3.7818 | 17.9284 | 5 | Evening |
| 21 | 3.2342 | 18.7128 | 5 | Evening |
| 22 | 2.4795 | 20.4524 | 5 | Evening |
| 23 | 1.8303 | 22.846 | 6 | Late Night |![image.png](attachment:image.png)

## Automated Binning:  BODY_TYP

The CRSS dataset in these six years differentiates 68 different vehicle body types.  Some of them, like "4: 4-Door Sedan, Hardtop" and "14: Compact Utility" are common, with 36% and 16% of crash persons, respectively.  Some like "21: Large Van" are less common (1%), and some are rare, like "32: Pickup With Slide-in Camper (2016-2017 Only)" (0.0007%).  

We want to put the 68 codes into about five bins by likelihood of going to the hospital.

To bin a feature like BODY_TYP, the code in this notebook orders the CRSS codes by proportion of crash persons going to the hospital, then assigns the codes to about five bins so that approximately the same number of crash persons are in each bin.  Large categories like "4: 4-Door Sedan, Hardtop" will be their own bin.  

Unsurprisingly, many of the codes in the most dangerous bin are motorcycles, and many of the codes in the least dangerous bin are large trucks.  

The table below shows some of the data that the code below considers when cutting the bins.  CRSS codes 4 and 14 are large enough to get their own bins.  Codes 20 and 34 are not large enough to get their own bins, but too large to be in the same bin.  This notebook ouputs such a table for each feature in $\LaTeX$ format.

| BODY_TYP | % of Crash Persons | % to Hospital | Our Bin |
|---|---|---|---|
| 86 | 0.0003 | 100.0000 | 0 |
| ... | | | |
| 1 | 0.6528 | 16.2667 | 0 |
| 2 | 3.0509 | 16.085 | 0 |
| 19 | 0.9264 | 15.9881 | 0 |
| 52 | 0.1562 | 15.9703 | 0 |
| 59 | 0.0309 | 15.9624 | 0 |
|||||
| 4 | 36.1961 | 15.9386 | 1 |
|||||
| 30 | 0.3609 | 15.7154 | 2 |
| 5 | 2.5745 | 14.8298 | 2 |
| 9 | 2.8609 | 14.6233 | 2 |
| 10 | 0.0142 | 14.2857 | 2 |
| 91 | 0.001 | 14.2857 | 2 |
| 6 | 5.2201 | 14.1666 | 2 |
| 16 | 0.2965 | 14.09 | 2 |
|||||
| 14 | 16.1724 | 13.823 | 3 |
|||||
| 22 | 0.0132 | 13.1868 | 4 |
| 20 | 4.1037 | 12.9021 | 4 |
| 40 | 0.0717 | 12.5506 | 4 |
|||||
| 34 | 9.824 | 11.7167 | 5 |
| 29 | 0.2 | 11.4576 | 5 |
| 15 | 5.4602 | 11.2749 | 5 |
| 31 | 1.4085 | 11.2358 | 5 |
| 17 | 0.0149 | 10.6796 | 5 |
| ... | | | |
| 41 | 0.0001 | 0.0000 | 5 |

The cell below is actual output from this notebook, in a format we could cut and paste into the next notebook.  The comments show the percentage of crash persons in each bin.

In [2]:
A = [
        ['0', [86,87,82,83,89,81,84,80,88,85,90,11,96,95,97,45,58,12,32,8,42,3,1,2,19,52,59,]], #  9.0438 %
        ['1', [4,]], #  36.1961 %
        ['2', [30,5,9,10,91,6,16,]], #  11.3281 %
        ['3', [14,]], #  16.1724 %
        ['4', [22,20,40,]], #  14.0126 %
        ['5', [34,29,15,31,17,39,55,28,21,93,92,48,50,7,51,61,67,63,62,66,65,78,64,72,60,71,73,94,41,]], #  13.2471 %
        ['Unknowns', [98, 99, 49, 79, ]]
    ]

# Setup
## Import Libraries

In [3]:
import sys, copy, math, time

print ('Python version: {}'.format(sys.version))

from IPython.display import display, HTML

from collections import Counter

import numpy as np
print ('NumPy version: {}'.format(np.__version__))
np.set_printoptions(suppress=True)

import pandas as pd
print ('Pandas version:  {}'.format(pd.__version__))
pd.set_option('display.max_rows', 500)

print ('Finished Importing Libraries')

Python version: 3.9.16 (main, Dec  7 2022, 10:02:13)
[Clang 14.0.0 (clang-1400.0.29.202)]
NumPy version: 1.24.0
Pandas version:  1.5.2
Finished Importing Libraries

## Import Data

In [4]:
def Import_Data():
    print ('Import_Data()')
    filename = '../../Big_Files/CRSS_Merged_Raw_Data.csv'
    data = pd.read_csv(filename, index_col=None)
    
    print ('data.shape: ', data.shape)
    
    return data

#Import_Data()

# Tools

## Narrow_Dataset()

In [5]:
def Narrow_Dataset(data, Features):
    print ('Narrow_Dataset()')
    data_narrow = pd.DataFrame()
  

    for f in Features:
        data_narrow[f] = data[f]
        
    data_narrow = data_narrow.reindex(sorted(data_narrow.columns), axis=1)    
    
    print ()
    return data_narrow

## Feature_Names()

In [6]:
def Feature_Names(data, Named_Features):
    print ('Feature_Names')
    D = {}
    for f in Named_Features:
        g = f + 'NAME'
        A = pd.concat([data[f],data[g]], axis=1)
        A.drop_duplicates(inplace=True)
        A.dropna(inplace=True)
#        print (f)
#        print (len(A))
#        print (A.head())
#        print ()
        B = dict(zip(A[f],A[g]))
        D[f] = B
#        print (B)
#        print ()
#    print (D)
    print ()
    return D

## Remove_Unknowns_in_Feature()

In [7]:
def Remove_Unknowns_in_Feature(data, feature):
    
    Unknowns = {     
    # Accident
        'DAY_WEEK': [9],
        'HOUR': [99],
        'INT_HWY': [9],
        'LGT_COND': [8,9],
#        'MAN_COLL': [98,99],
        'MONTH': [],
        'REL_ROAD': [98,99],
        'RELJCT2': [98,99],
        'TYP_INT': [98,99],
        'WEATHER': [98,99],
    # Vehicle
        'BDYTYP_IM': [],
        'BODY_TYP': [98, 99, 49, 79],
        'BUS_USE': [98, 99],
        'DR_ZIP': [9998, 9999],
        'EMER_USE': [8, 9],
        'MAKE': [99],
        'MOD_YEAR': [9998, 9999],
        'MODEL': [],
        'NUMOCCS': [99],
        'VALIGN': [8, 9],
        'VNUM_LAN': [8, 9],
        'VPROFILE': [8, 9],
        'VSPD_LIM': [98, 99],
        'VSURCOND': [98, 99],
        'VTRAFCON': [97, 99],
        'VTRAFWAY': [8, 9],
    # Person
        'SEX_IM': [],
        'AGE': [998,999,],
        'HOSPITAL': [],
        'LOCATION': [98,99,],
        'PER_TYP': [],        
    }
    

    if feature in Unknowns.keys():
        print ('Remove_Unknowns_in_Feature ', feature, Unknowns[feature], len(data[data[feature].isin(Unknowns[feature])]), ' unknown')
        data_temp = data[~data[feature].isin(Unknowns[feature])]
        return data_temp, Unknowns[feature]
    else:
        data_temp = data
        return data_temp, []
    print ()

## Correlation()

In [8]:
def Correlation(data, target, feature, value, name):
    TN = 0
    FP = 0
    FN = 0
    TP = 0
    contingency_matrix = pd.crosstab(data[target], data[feature])
    cm = contingency_matrix.values.tolist()
    if len(cm)==2 and len(cm[0])==2:
        corr = cm[1][1] / (cm[0][1] + cm[1][1])
        per = (cm[0][1] + cm[1][1])/(cm[0][0] + cm[0][1] + cm[1][0] + cm[1][1])
    else:
        corr = 0
        per = 0
    per = round(per*100,4)
    corr = round(corr*100,4)
#    print ("    - ", feature)
#    print ("    - ", value)
#    print ("    - ", name)
#    print (contingency_matrix)
#    print ('        - per = ', per)
#    print ("        - corr = ", corr)
#    print ()
    return (per, corr)

def Correlation_by_Value(data, target, feature, Feature_Names_Dict, Unknowns):
# I decided against the np.unique because it treats each nan as a separate entry.
#    V = np.unique(data[feature].values) 
    V = data[feature].unique()
#    print (V)
    B = []

    for value in V:
        A = pd.DataFrame()
        A[feature] = data[feature].apply(lambda x: 1 if x==value else 0)
        A[target] = data[target]
        if feature in Feature_Names_Dict:
            if value in Feature_Names_Dict[feature]:
                name = Feature_Names_Dict[feature][value]
            else:
                name=str(value)
        else:
            name = str(value)
#        if len(name)>30:
#            name = name[:30]
        per, corr = Correlation(A, target, feature, value, name)
        B.append([feature, value, name, per, corr])
#    print (feature)
    B = sorted(B, key=lambda x:x[4], reverse=True)
    for b in B:
        c = b[1]
        try:
            c = int(c)
        except:
            c=c
        else:
            c = int(c)
#        print (c, end=',')
#    print ()
#    print ()

    # Print grouped into 100/p blocks of same size
    print ("    feature = '%s'" % feature)
    print ('    A = [')
    p = 20
    s = 0.0
    s2 = 0.0
    n=0
    print ("        ['%d', [" % n , end='')
    for b in B:
        t = s + b[3]
        if b[3]<10:
            s2 = s2 + b[3]
        q = int(s/p)
        r = int((t-0.001)/p)
        if r>q or b[3]>10:
            print ("]], # ", round(s2,4), '%')
            s2 = 0.0
            n += 1
            print ("        ['%d', [" % n , end='')
        s = t
        
        c = b[1]
        try:
            c = int(c)
        except:
            c=c
        else:
            c = int(c)
        print (c, end=',')
        if b[3]>10:
            print ("]], # ", round(b[3],4), '%')
            s2=0.0
            n += 1
            print ("        ['%d', [" % n , end='')
    print ("]], # ", round(s2,4), '%')
    print ("        ['Unknowns', [", end='')
    for u in Unknowns:
        print (u, end=', ')
    print ("]]" )
    print ('    ]')
    print ('    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)')
    print ()
    
    C = pd.DataFrame(B)
    C.columns = ['Feature', 'Code', 'Name', 'Per', 'Corr']
#    C.drop(C[C['Per'] < 0.1].index, inplace=True)
#    print (C)
    display(C)

    TeX = open('../Correlation/Correlation_' + feature + '.tex', 'w')
    E = [c for c in B if c[3]>=0.0]
    
        
    
    for c in E:
        a = c[0]
        b = c[1]
        d = c[2]
        e = "{:.4f}".format(c[3])
        f = "{:.4f}".format(c[4])
        TeX.write('\t & \\verb|%s| & %s & %s & %s & %s \\cr\n' % (a,b,d,e,f))
    

    TeX = open('../Correlation/Correlation_Ordered_' + feature + '.tex', 'w')
    E = sorted(B, key=lambda x:x[1], reverse=False)

    
    for c in E:
        a = c[0]
        b = c[1]
        d = c[2]
        e = "{:.4f}".format(c[3])
        f = "{:.4f}".format(c[4])
        TeX.write('\t & \\verb|%s| & %s & %s & %s & %s \\cr\n' % (a,b,d,e,f))
    

    print ()
    return B

def Correlation_All(data, target, Feature_Names_Dict):
    print ('Correlation_All')
    
    C = []
    for feature in data:
        data_temp, Unknowns = Remove_Unknowns_in_Feature(data, feature)
        U = data_temp[feature].unique()
#        print (feature, len(U))
        if len(U)<10000:
            B = Correlation_by_Value(
                data_temp, target, feature, Feature_Names_Dict, Unknowns
            )
            for b in B:
                C.append(b)
#            print ()
#        print ()
#    for c in C:
#        print (c)
#    print ()
    C = sorted(C, key=lambda x:x[4], reverse=True)
    D = pd.DataFrame(C)
    D.columns = ['Feature', 'Code', 'Name', 'Per', 'Corr']
    print (D)
    print ()
    
    D.drop(D[D['Per'] < 0.5].index, inplace=True)
    print (D)
    print ()
    
    TeX = open('../Correlation/Correlation.tex', 'w')
    E = [c for c in C if c[3]>=0.5]
    
    for c in E:
        a = c[0]
        b = c[1]
        d = c[2]
        e = "{:.4f}".format(c[3])
        f = "{:.4f}".format(c[4])
        TeX.write('\\verb|%s| & %s & %s & %s & %s \\cr\n' % (a,b,d,e,f))
    
    return 0

# Main()

In [9]:
def Main():
    target = 'HOSPITAL'
    data = Import_Data()
    
    Features = [
    # Accident Dataset
        'DAY_WEEK',
        'HOUR',
        'INT_HWY',
        'LGT_COND',
        'MONTH',
#        'PEDS',
        'PERMVIT',
        'PERNOTMVIT',
        'PJ',
        'PSU',
        'PVH_INVL',
        'REGION',
        'REL_ROAD',
        'RELJCT1',
        'RELJCT2',
        'SCH_BUS',
        'TYP_INT',
        'URBANICITY',
        'VE_FORMS',
        'VE_TOTAL',
        'WEATHER',
        'WRK_ZONE',
        'YEAR',
    # Vehicle Dataset
        'BODY_TYP',
        'BUS_USE',
        'DR_ZIP',
        'EMER_USE',
        'MAKE',
        'MOD_YEAR',
        'MODEL',
        'NUMOCCS',
        'VALIGN',
        'VNUM_LAN',
        'VPROFILE',
        'VSPD_LIM',
        'VSURCOND',
        'VTRAFCON',
        'VTRAFWAY',
    # Person Dataset
        'AGE',
        'HOSPITAL',
        'LOCATION',
        'PER_TYP',
        'SEX',
    ]

    data = Narrow_Dataset(data, Features)
    
    print ('Features in data, with Number of Unique Values and Number of Blank Values')
    for feature in data:
        U = data[feature].unique()
        s = data[feature].isna().sum()
        print (feature, len(U), s)
    print ()
        
#    Feature_Names_Dict = Feature_Names(data, Features)
    Feature_Names_Dict = {}

#    print (Feature_Names_Dict)
    
    Correlation_All(data, target, Feature_Names_Dict)


Main()

Import_Data()
data.shape:  (713566, 118)
Narrow_Dataset()

Features in data, with Number of Unique Values and Number of Blank Values
AGE 116 0
BODY_TYP 72 0
BUS_USE 9 0
DAY_WEEK 7 0
DR_ZIP 18508 0
EMER_USE 8 0
HOSPITAL 2 0
HOUR 25 0
INT_HWY 3 0
LGT_COND 9 0
LOCATION 1 0
MAKE 70 0
MODEL 141 0
MOD_YEAR 85 0
MONTH 12 0
NUMOCCS 65 0
PERMVIT 25 0
PERNOTMVIT 8 0
PER_TYP 3 0
PJ 424 0
PSU 60 0
PVH_INVL 12 0
REGION 4 0
RELJCT1 4 0
RELJCT2 15 0
REL_ROAD 13 0
SCH_BUS 2 0
SEX 4 0
TYP_INT 11 0
URBANICITY 2 0
VALIGN 7 0
VE_FORMS 14 0
VE_TOTAL 14 0
VNUM_LAN 10 0
VPROFILE 9 0
VSPD_LIM 20 0
VSURCOND 13 0
VTRAFCON 19 0
VTRAFWAY 9 0
WEATHER 13 0
WRK_ZONE 5 0
YEAR 6 0

Correlation_All
Remove_Unknowns_in_Feature  AGE [998, 999] 42380  unknown
    feature = 'AGE'
    A = [
        ['0', [106,119,105,117,100,108,118,94,91,98,90,92,116,101,82,89,87,83,97,88,86,84,95,85,81,77,79,76,78,80,74,96,75,71,93,70,72,73,57,63,62,54,66,68,67,60,58,69,65,61,64,51,]], #  20.5399 %
        ['1', [55,32,52,56,59,53,33,35,30,38,29,28,]], #  20.398 %
        ['2', [24,40,49,27,48,26,41,22,43,31,50,]], #  19.7373 %
        ['3', [23,34,36,45,46,47,37,25,44,21,42,]], #  19.4815 %
        ['4', [19,20,39,14,18,15,10,8,13,0,17,7,9,11,12,16,6,5,4,2,1,3,115,99,102,111,109,120,]], #  19.843 %
        ['Unknowns', [998, 999, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name     Per      Corr
0       AGE   106  106  0.0001  100.0000
1       AGE   119  119  0.0010   71.4286
2       AGE   105  105  0.0006   50.0000
3       AGE   117  117  0.0003   50.0000
4       AGE   100  100  0.0013   33.3333
5       AGE   108  108  0.0004   33.3333
6       AGE   118  118  0.0004   33.3333
7       AGE    94   94  0.0130   27.5862
8       AGE    91   91  0.0353   27.0042
9       AGE    98   98  0.0028   26.3158
10      AGE    90   90  0.0487   25.6881
11      AGE    92   92  0.0325   25.6881
12      AGE   116  116  0.0012   25.0000
13      AGE   101  101  0.0006   25.0000
14      AGE    82   82  0.2065   24.7475
15      AGE    89   89  0.0672   23.7251
16      AGE    87   87  0.1015   23.6417
17      AGE    83   83  0.1771   23.1287
18      AGE    97   97  0.0066   22.7273
19      AGE    88   88  0.0837   22.4199
20      AGE    86   86  0.1146   22.2367
21      AGE    84   84  0.1496   22.1116
22      AGE    95   95  0.0125   21.4286
23      AGE    85   85  0.1208   21.3317
24      AGE    81   81  0.2238   21.2383
25      AGE    77   77  0.3200   21.0894
26      AGE    79   79  0.2677   21.0351
27      AGE    76   76  0.3446   20.7090
28      AGE    78   78  0.3081   20.4545
29      AGE    80   80  0.2283   20.2350
30      AGE    74   74  0.4307   19.4396
31      AGE    96   96  0.0085   19.2982
32      AGE    75   75  0.3971   18.4991
33      AGE    71   71  0.5753   18.4667
34      AGE    93   93  0.0238   18.1250
35      AGE    70   70  0.6013   17.9386
36      AGE    72   72  0.5267   17.9066
37      AGE    73   73  0.4765   17.8862
38      AGE    57   57  1.1872   17.6832
39      AGE    63   63  0.9184   17.6184
40      AGE    62   62  0.9605   17.5741
41      AGE    54   54  1.2411   17.5630
42      AGE    66   66  0.7436   17.5115
43      AGE    68   68  0.6854   17.3913
44      AGE    67   67  0.7175   17.2135
45      AGE    60   60  1.0891   17.2093
46      AGE    58   58  1.1608   17.1737
47      AGE    69   69  0.6500   17.1442
48      AGE    65   65  0.8130   17.1156
49      AGE    61   61  1.0309   16.9967
50      AGE    64   64  0.8589   16.9297
51      AGE    51   51  1.3071   16.8357
52      AGE    55   55  1.2657   16.8099
53      AGE    32   32  1.7949   16.6099
54      AGE    52   52  1.2748   16.5732
55      AGE    56   56  1.2241   16.5652
56      AGE    59   59  1.1185   16.4646
57      AGE    53   53  1.2330   16.3968
58      AGE    33   33  1.7964   16.3225
59      AGE    35   35  1.7344   16.2529
60      AGE    30   30  1.9953   16.2336
61      AGE    38   38  1.5718   16.2180
62      AGE    29   29  2.1027   16.2049
63      AGE    28   28  2.1706   16.1507
64      AGE    24   24  2.3815   16.1161
65      AGE    40   40  1.4832   16.0924
66      AGE    49   49  1.3503   16.0764
67      AGE    27   27  2.2097   16.0138
68      AGE    48   48  1.3305   16.0022
69      AGE    26   26  2.2798   15.9652
70      AGE    41   41  1.4696   15.9367
71      AGE    22   22  2.5419   15.8314
72      AGE    43   43  1.3761   15.8185
73      AGE    31   31  1.9148   15.8030
74      AGE    50   50  1.3247   15.7800
75      AGE    23   23  2.4567   15.7681
76      AGE    34   34  1.7275   15.7223
77      AGE    36   36  1.6587   15.7101
78      AGE    45   45  1.3841   15.6405
79      AGE    46   46  1.3585   15.6175
80      AGE    47   47  1.3475   15.6015
81      AGE    37   37  1.5851   15.5748
82      AGE    25   25  2.3610   15.4982
83      AGE    44   44  1.3716   15.4573
84      AGE    21   21  2.6124   15.4215
85      AGE    42   42  1.3954   15.3641
86      AGE    19   19  2.6797   15.2785
87      AGE    20   20  2.6227   15.1111
88      AGE    39   39  1.5288   15.0083
89      AGE    14   14  0.6049   14.5320
90      AGE    18   18  2.6914   14.3324
91      AGE    15   15  0.8040   14.0289
92      AGE    10   10  0.5428   13.9171
93      AGE     8    8  0.5325   13.7661
94      AGE    13   13  0.5189   13.5802
95      AGE     0    0  0.4792   13.5572
96      AGE    17   17  2.2366   13.5492
97      AGE     7    7  0.5389   13.0218
98      AGE     9    9  0.5362   12.9758
99      AGE    11   11  0.5152   12.9265
100     AGE    12   12  0.5192   12.5395
101     AGE    16   16  1.6727   12.4521
102     AGE     6    6  0.5337   12.2836
103     AGE     5    5  0.5523   12.1122
104     AGE     4    4  0.5882   11.4742
105     AGE     2    2  0.5873   10.7560
106     AGE     1    1  0.6308   10.4629
107     AGE     3    3  0.6022   10.0198
108     AGE   115  115  0.0007    0.0000
109     AGE    99   99  0.0027    0.0000
110     AGE   102  102  0.0006    0.0000
111     AGE   111  111  0.0001    0.0000
112     AGE   109  109  0.0003    0.0000
113     AGE   120  120  0.0001    0.0000

Remove_Unknowns_in_Feature  BODY_TYP [98, 99, 49, 79] 24194  unknown
    feature = 'BODY_TYP'
    A = [
        ['0', [86,87,82,83,89,81,84,80,88,85,90,11,96,95,97,45,58,12,32,8,42,3,1,2,19,52,59,]], #  9.0438 %
        ['1', [4,]], #  36.1961 %
        ['2', [30,5,9,10,91,6,16,]], #  11.3281 %
        ['3', [14,]], #  16.1724 %
        ['4', [22,20,40,]], #  14.0126 %
        ['5', [34,29,15,31,17,39,55,28,21,93,92,48,50,7,51,61,67,63,62,66,65,78,64,72,60,71,73,94,41,]], #  13.2471 %
        ['Unknowns', [98, 99, 49, 79, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

     Feature  Code Name      Per      Corr
0   BODY_TYP    86   86   0.0003  100.0000
1   BODY_TYP    87   87   0.0009   83.3333
2   BODY_TYP    82   82   0.0119   69.5122
3   BODY_TYP    83   83   0.0421   67.5862
4   BODY_TYP    89   89   0.1387   66.7364
5   BODY_TYP    81   81   0.1020   65.2916
6   BODY_TYP    84   84   0.1584   62.9121
7   BODY_TYP    80   80   2.3416   62.2476
8   BODY_TYP    88   88   0.0276   60.0000
9   BODY_TYP    85   85   0.0122   52.3810
10  BODY_TYP    90   90   0.0261   43.3333
11  BODY_TYP    11   11   0.0009   33.3333
12  BODY_TYP    96   96   0.0084   29.3103
13  BODY_TYP    95   95   0.0081   28.5714
14  BODY_TYP    97   97   0.0057   25.6410
15  BODY_TYP    45   45   0.0017   25.0000
16  BODY_TYP    58   58   0.0171   24.5763
17  BODY_TYP    12   12   0.0026   22.2222
18  BODY_TYP    32   32   0.0007   20.0000
19  BODY_TYP     8    8   0.5647   17.4416
20  BODY_TYP    42   42   0.0009   16.6667
21  BODY_TYP     3    3   0.7540   16.4294
22  BODY_TYP     1    1   0.6528   16.2667
23  BODY_TYP     2    2   3.0509   16.0850
24  BODY_TYP    19   19   0.9264   15.9881
25  BODY_TYP    52   52   0.1562   15.9703
26  BODY_TYP    59   59   0.0309   15.9624
27  BODY_TYP     4    4  36.1961   15.9386
28  BODY_TYP    30   30   0.3609   15.7154
29  BODY_TYP     5    5   2.5745   14.8298
30  BODY_TYP     9    9   2.8609   14.6233
31  BODY_TYP    10   10   0.0142   14.2857
32  BODY_TYP    91   91   0.0010   14.2857
33  BODY_TYP     6    6   5.2201   14.1666
34  BODY_TYP    16   16   0.2965   14.0900
35  BODY_TYP    14   14  16.1724   13.8230
36  BODY_TYP    22   22   0.0132   13.1868
37  BODY_TYP    20   20   4.1037   12.9021
38  BODY_TYP    40   40   0.0717   12.5506
39  BODY_TYP    34   34   9.8240   11.7167
40  BODY_TYP    29   29   0.2000   11.4576
41  BODY_TYP    15   15   5.4602   11.2749
42  BODY_TYP    31   31   1.4085   11.2358
43  BODY_TYP    17   17   0.0149   10.6796
44  BODY_TYP    39   39   0.4355   10.5596
45  BODY_TYP    55   55   0.0524    9.6953
46  BODY_TYP    28   28   0.0122    9.5238
47  BODY_TYP    21   21   1.1817    8.9737
48  BODY_TYP    93   93   0.0067    8.6957
49  BODY_TYP    92   92   0.0274    8.4656
50  BODY_TYP    48   48   0.1066    8.4354
51  BODY_TYP    50   50   0.2037    7.7635
52  BODY_TYP     7    7   0.0071    6.1224
53  BODY_TYP    51   51   0.0104    5.5556
54  BODY_TYP    61   61   0.6789    5.2778
55  BODY_TYP    67   67   0.4765    4.9619
56  BODY_TYP    63   63   0.4919    4.3940
57  BODY_TYP    62   62   0.3238    4.0323
58  BODY_TYP    66   66   1.7691    3.4602
59  BODY_TYP    65   65   0.0413    3.1579
60  BODY_TYP    78   78   0.1178    2.7094
61  BODY_TYP    64   64   0.1733    2.5941
62  BODY_TYP    72   72   0.0061    2.3810
63  BODY_TYP    60   60   0.0292    1.4925
64  BODY_TYP    71   71   0.0064    0.0000
65  BODY_TYP    73   73   0.0038    0.0000
66  BODY_TYP    94   94   0.0016    0.0000
67  BODY_TYP    41   41   0.0001    0.0000

Remove_Unknowns_in_Feature  BUS_USE [98, 99] 7042  unknown
    feature = 'BUS_USE'
    A = [
        ['0', [5,6,]], #  0.1823 %
        ['1', [0,]], #  99.5662 %
        ['2', [7,8,1,4,]], #  0.2515 %
        ['Unknowns', [98, 99, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

   Feature  Code Name      Per     Corr
0  BUS_USE     5    5   0.0178  30.9524
1  BUS_USE     6    6   0.1645  16.6093
2  BUS_USE     0    0  99.5662  15.2748
3  BUS_USE     7    7   0.0164  13.7931
4  BUS_USE     8    8   0.0076   9.2593
5  BUS_USE     1    1   0.2194   8.1935
6  BUS_USE     4    4   0.0081   5.2632

Remove_Unknowns_in_Feature  DAY_WEEK [9] 0  unknown
    feature = 'DAY_WEEK'
    A = [
        ['0', []], #  0.0 %
        ['1', [1,]], #  11.306 %
        ['2', []], #  0.0 %
        ['3', [7,]], #  13.834 %
        ['4', []], #  0.0 %
        ['5', [2,]], #  13.7551 %
        ['6', []], #  0.0 %
        ['7', [4,]], #  14.6777 %
        ['8', []], #  0.0 %
        ['9', [5,]], #  15.014 %
        ['10', []], #  0.0 %
        ['11', [3,]], #  14.3922 %
        ['12', []], #  0.0 %
        ['13', [6,]], #  17.0209 %
        ['14', []], #  0.0 %
        ['Unknowns', [9, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name      Per     Corr
0  DAY_WEEK     1    1  11.3060  18.2198
1  DAY_WEEK     7    7  13.8340  16.7877
2  DAY_WEEK     2    2  13.7551  14.7241
3  DAY_WEEK     4    4  14.6777  14.4718
4  DAY_WEEK     5    5  15.0140  14.4164
5  DAY_WEEK     3    3  14.3922  14.2369
6  DAY_WEEK     6    6  17.0209  14.0052

Remove_Unknowns_in_Feature  DR_ZIP [9998, 9999] 0  unknown
Remove_Unknowns_in_Feature  EMER_USE [8, 9] 5064  unknown
    feature = 'EMER_USE'
    A = [
        ['0', [6,5,]], #  0.197 %
        ['1', [0,]], #  99.6821 %
        ['2', [3,4,2,]], #  0.1208 %
        ['Unknowns', [8, 9, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name      Per     Corr
0  EMER_USE     6    6   0.0710  21.0736
1  EMER_USE     5    5   0.1260  17.6932
2  EMER_USE     0    0  99.6821  15.2171
3  EMER_USE     3    3   0.0113  13.7500
4  EMER_USE     4    4   0.0189  12.6866
5  EMER_USE     2    2   0.0906  11.2150

Remove_Unknowns_in_Feature  HOSPITAL [] 0  unknown
    feature = 'HOSPITAL'
    A = [
        ['0', []], #  0.0 %
        ['1', [0,]], #  15.1291 %
        ['2', []], #  0.0 %
        ['3', [1,]], #  15.1291 %
        ['4', []], #  0.0 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name      Per   Corr
0  HOSPITAL     0    0  15.1291  100.0
1  HOSPITAL     1    1  15.1291  100.0

Remove_Unknowns_in_Feature  HOUR [99] 2084  unknown
    feature = 'HOUR'
    A = [
        ['0', [3,2,1,4,0,23,5,22,21,20,6,]], #  24.5247 %
        ['1', [19,10,9,14,]], #  20.0693 %
        ['2', [11,18,13,]], #  19.5796 %
        ['3', [12,8,16,]], #  17.9066 %
        ['4', [7,15,17,]], #  17.9198 %
        ['Unknowns', [99, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

   Feature  Code Name     Per     Corr
0     HOUR     3    3  0.7306  26.8372
1     HOUR     2    2  0.9483  26.6044
2     HOUR     1    1  1.0665  26.5419
3     HOUR     4    4  0.7089  25.6741
4     HOUR     0    0  1.3440  23.0705
5     HOUR    23   23  1.8303  22.8460
6     HOUR     5    5  1.1962  21.2548
7     HOUR    22   22  2.4795  20.4524
8     HOUR    21   21  3.2342  18.7128
9     HOUR    20   20  3.7818  17.9284
10    HOUR     6    6  2.4013  17.1788
11    HOUR    19   19  4.8031  16.2731
12    HOUR    10   10  4.0790  14.8444
13    HOUR     9    9  3.8258  14.3828
14    HOUR    14   14  7.0741  14.1841
15    HOUR    11   11  5.0904  14.1232
16    HOUR    18   18  7.0147  14.0458
17    HOUR    13   13  6.2852  14.0212
18    HOUR    12   12  6.2797  13.4761
19    HOUR     8    8  4.5183  13.3792
20    HOUR    16   16  8.6935  13.3526
21    HOUR     7    7  4.6948  13.1665
22    HOUR    15   15  8.6077  12.9617
23    HOUR    17   17  9.3121  12.6166

Remove_Unknowns_in_Feature  INT_HWY [9] 66  unknown
    feature = 'INT_HWY'
    A = [
        ['0', []], #  0.0 %
        ['1', [0,]], #  89.3153 %
        ['2', []], #  0.0 %
        ['3', [1,]], #  10.6847 %
        ['4', []], #  0.0 %
        ['Unknowns', [9, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

   Feature  Code Name      Per     Corr
0  INT_HWY     0    0  89.3153  15.1501
1  INT_HWY     1    1  10.6847  14.9564

Remove_Unknowns_in_Feature  LGT_COND [8, 9] 4049  unknown
    feature = 'LGT_COND'
    A = [
        ['0', [2,4,]], #  9.4447 %
        ['1', [3,]], #  15.6344 %
        ['2', [5,6,]], #  2.9786 %
        ['3', [1,]], #  71.9161 %
        ['4', [7,]], #  0.0261 %
        ['Unknowns', [8, 9, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name      Per     Corr
0  LGT_COND     2    2   8.1829  22.7854
1  LGT_COND     4    4   1.2618  17.6812
2  LGT_COND     3    3  15.6344  16.9451
3  LGT_COND     5    5   2.4088  15.5052
4  LGT_COND     6    6   0.5698  15.1125
5  LGT_COND     1    1  71.9161  13.8767
6  LGT_COND     7    7   0.0261  12.9730

Remove_Unknowns_in_Feature  LOCATION [98, 99] 0  unknown
    feature = 'LOCATION'
    A = [
        ['0', [0,]], #  0.0 %
        ['Unknowns', [98, 99, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name  Per  Corr
0  LOCATION     0    0    0     0

Remove_Unknowns_in_Feature  MAKE [99] 13241  unknown
    feature = 'MAKE'
    A = [
        ['0', [71,74,76,73,72,50,77,53,98,64,65,43,21,9,92,22,52,14,24,18,37,63,]], #  28.0121 %
        ['1', [35,55,6,39,36,13,]], #  6.6778 %
        ['2', [20,]], #  12.6246 %
        ['3', [69,67,34,]], #  1.5972 %
        ['4', [49,]], #  11.6921 %
        ['5', []], #  0.0 %
        ['6', [12,]], #  13.267 %
        ['7', [19,41,30,58,]], #  8.0808 %
        ['8', [2,42,54,7,25,47,93,23,59,48,3,38,62,32,51,45,31,29,90,10,94,86,84,82,85,89,87,97,33,46,1,]], #  18.0481 %
        ['Unknowns', [99, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

   Feature  Code Name      Per     Corr
0     MAKE    71   71   0.0257  66.6667
1     MAKE    74   74   0.0026  66.6667
2     MAKE    76   76   0.3551  64.0933
3     MAKE    73   73   0.2804  62.3727
4     MAKE    72   72   0.9141  62.1368
5     MAKE    50   50   0.0297  60.0962
6     MAKE    77   77   0.0206  52.7778
7     MAKE    53   53   0.4529  46.9735
8     MAKE    98   98   0.6768  32.9325
9     MAKE    64   64   0.0019  30.7692
10    MAKE    65   65   0.0124  25.2874
11    MAKE    43   43   0.0006  25.0000
12    MAKE    21   21   0.1688  20.4738
13    MAKE     9    9   0.0427  20.0669
14    MAKE    92   92   0.0811  17.9577
15    MAKE    22   22   0.8645  17.5091
16    MAKE    52   52   0.8200  17.3254
17    MAKE    14   14   0.5239  17.2254
18    MAKE    24   24   0.4842  16.8977
19    MAKE    18   18   1.4188  16.6969
20    MAKE    37   37   9.3996  16.5811
21    MAKE    63   63   3.2402  16.3273
22    MAKE    35   35   8.1955  15.9056
23    MAKE    55   55   3.9465  15.6813
24    MAKE     6    6   1.9862  15.5068
25    MAKE    39   39   0.1007  15.1773
26    MAKE    36   36   0.0635  15.0562
27    MAKE    13   13   0.5809  14.9459
28    MAKE    20   20  12.6246  14.8349
29    MAKE    69   69   0.1688  14.7208
30    MAKE    67   67   0.1287  14.6504
31    MAKE    34   34   1.2997  14.5243
32    MAKE    49   49  11.6921  14.1030
33    MAKE    12   12  13.2670  13.7506
34    MAKE    19   19   0.9039  13.7441
35    MAKE    41   41   1.4753  13.7050
36    MAKE    30   30   1.5380  13.6385
37    MAKE    58   58   0.8873  13.6144
38    MAKE     2    2   3.2763  13.3406
39    MAKE    42   42   1.3235  13.2269
40    MAKE    54   54   0.9853  13.1449
41    MAKE     7    7   5.9167  13.0563
42    MAKE    25   25   0.0077  12.9630
43    MAKE    47   47   0.0483  12.7219
44    MAKE    93   93   0.0113  12.6582
45    MAKE    23   23   2.6606  12.3866
46    MAKE    59   59   1.4172  12.3728
47    MAKE    48   48   1.3322  11.3290
48    MAKE     3    3   0.0571  11.0000
49    MAKE    38   38   0.1776  10.6913
50    MAKE    62   62   0.1913  10.3731
51    MAKE    32   32   0.5233   9.8772
52    MAKE    51   51   0.6054   9.4104
53    MAKE    45   45   0.0878   8.9431
54    MAKE    31   31   0.0131   8.6957
55    MAKE    29   29   0.0990   8.6580
56    MAKE    90   90   0.0525   8.4239
57    MAKE    10   10   0.0017   8.3333
58    MAKE    94   94   0.0198   7.1942
59    MAKE    86   86   0.1789   4.6289
60    MAKE    84   84   0.5006   4.2499
61    MAKE    82   82   0.9186   4.0727
62    MAKE    85   85   0.2814   4.0589
63    MAKE    89   89   0.0119   3.6145
64    MAKE    87   87   0.3318   3.2272
65    MAKE    97   97   0.2929   0.9264
66    MAKE    33   33   0.0001   0.0000
67    MAKE    46   46   0.0001   0.0000
68    MAKE     1    1   0.0004   0.0000

Remove_Unknowns_in_Feature  MODEL [] 0  unknown
    feature = 'MODEL'
    A = [
        ['0', [63,709,704,703,701,706,705,702,707,799,734,733,907,739,56,16,12,11,4,19,471,29,399,59,22,445,20,50,9,6,52,3,37,408,18,43,7,480,]], #  20.3837 %
        ['1', [2,21,13,17,406,1,36,38,15,988,25,444,39,31,48,32,424,47,27,35,998,]], #  20.5006 %
        ['2', [23,33,989,498,431,34,405,404,40,28,51,26,44,401,407,]], #  21.8534 %
        ['3', [402,499,46,54,24,42,442,49,443,425,473,55,403,41,53,398,441,472,446,423,]], #  21.123 %
        ['4', [481,421,14,999,422,45,470,5,463,482,8,983,461,10,462,870,981,58,982,483,883,809,57,882,426,880,881,806,898,850,884,808,804,997,890,732,908,466,805,598,902,731,599,904,474,60,427,]], #  16.1392 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name     Per     Corr
0     MODEL    63   63  0.0004  66.6667
1     MODEL   709  709  0.5265  65.9303
2     MODEL   704  704  0.0345  64.2276
3     MODEL   703  703  0.1806  62.8394
4     MODEL   701  701  0.0988  62.1277
5     MODEL   706  706  1.4322  61.7808
6     MODEL   705  705  0.4365  61.7335
7     MODEL   702  702  0.0203  60.6897
8     MODEL   707  707  0.0085  60.6557
9     MODEL   799  799  0.0013  55.5556
10    MODEL   734  734  0.0139  47.4747
11    MODEL   733  733  0.0036  42.3077
12    MODEL   907  907  0.0055  35.8974
13    MODEL   739  739  0.0137  31.6327
14    MODEL    56   56  0.0603  21.3953
15    MODEL    16   16  0.3960  20.3468
16    MODEL    12   12  0.0307  20.0913
17    MODEL    11   11  0.0036  19.2308
18    MODEL     4    4  0.0849  19.1419
19    MODEL    19   19  0.0905  18.5759
20    MODEL   471  471  0.8945  17.9226
21    MODEL    29   29  0.2764  17.9006
22    MODEL   399  399  4.1342  17.7458
23    MODEL    59   59  0.0048  17.6471
24    MODEL    22   22  0.7535  17.6306
25    MODEL   445  445  0.0112  17.5000
26    MODEL    20   20  0.5622  17.4227
27    MODEL    50   50  0.9965  17.2550
28    MODEL     9    9  0.3955  17.2218
29    MODEL     6    6  0.1909  17.1072
30    MODEL    52   52  0.2734  17.0169
31    MODEL     3    3  0.8121  16.9111
32    MODEL    37   37  3.3066  16.8976
33    MODEL   408  408  0.1308  16.7203
34    MODEL    18   18  0.6500  16.7098
35    MODEL    43   43  1.9415  16.6955
36    MODEL     7    7  0.2612  16.6845
37    MODEL   480  480  0.0092  16.6667
38    MODEL     2    2  1.3369  16.6457
39    MODEL    21   21  0.2332  16.5865
40    MODEL    13   13  0.1470  16.4919
41    MODEL    17   17  0.6693  16.4363
42    MODEL   406  406  0.1965  16.4051
43    MODEL     1    1  0.4555  16.2769
44    MODEL    36   36  0.5426  16.2448
45    MODEL    38   38  0.8563  16.1375
46    MODEL    15   15  0.0290  15.9420
47    MODEL   988  988  0.1462  15.9156
48    MODEL    25   25  1.0682  15.7570
49    MODEL   444  444  0.1659  15.7095
50    MODEL    39   39  0.9467  15.5736
51    MODEL    31   31  2.7365  15.4504
52    MODEL    48   48  0.3719  15.4484
53    MODEL    32   32  5.3708  15.3559
54    MODEL   424  424  0.0338  15.3527
55    MODEL    47   47  2.7461  15.3304
56    MODEL    27   27  0.4117  15.2825
57    MODEL    35   35  1.8960  15.2709
58    MODEL   998  998  0.0489  15.1862
59    MODEL    23   23  1.4285  15.1771
60    MODEL    33   33  1.2428  14.9301
61    MODEL   989  989  0.0548  14.8338
62    MODEL   498  498  0.0964  14.8256
63    MODEL   431  431  0.2488  14.7606
64    MODEL    34   34  1.5523  14.6430
65    MODEL   405  405  0.5617  14.5210
66    MODEL   404  404  2.4258  14.5176
67    MODEL    40   40  3.3504  14.3975
68    MODEL    28   28  0.4238  14.3849
69    MODEL    51   51  1.7996  14.3758
70    MODEL    26   26  0.2764  14.2495
71    MODEL    44   44  0.2151  14.1368
72    MODEL   401  401  4.2732  14.1283
73    MODEL   407  407  0.2595  13.8229
74    MODEL   402  402  5.0728  13.6499
75    MODEL   499  499  2.1336  13.6486
76    MODEL    46   46  0.9659  13.5229
77    MODEL    54   54  0.2975  13.4715
78    MODEL    24   24  1.1988  13.4557
79    MODEL    42   42  0.6077  13.4456
80    MODEL   442  442  1.6318  13.4146
81    MODEL    49   49  0.4147  13.3829
82    MODEL   443  443  0.3540  13.0245
83    MODEL   425  425  0.0650  12.9310
84    MODEL   473  473  0.3958  12.8187
85    MODEL    55   55  0.0842  12.8120
86    MODEL   403  403  2.5595  12.5493
87    MODEL    41   41  0.2848  12.3524
88    MODEL    53   53  0.1054  12.2340
89    MODEL   398  398  0.0723  12.2093
90    MODEL   441  441  1.7103  12.2009
91    MODEL   472  472  1.2857  12.1975
92    MODEL   446  446  0.0395  12.0567
93    MODEL   423  423  0.5608  11.6442
94    MODEL   481  481  6.3557  11.3688
95    MODEL   421  421  2.7461  11.2171
96    MODEL    14   14  0.0804  11.1498
97    MODEL   999  999  2.7363  11.0371
98    MODEL   422  422  1.8656  10.9675
99    MODEL    45   45  0.4033  10.8409
100   MODEL   470  470  0.0052  10.8108
101   MODEL     5    5  0.1616  10.5811
102   MODEL   463  463  0.0520  10.5121
103   MODEL   482  482  2.2386  10.3543
104   MODEL     8    8  0.1376   9.6741
105   MODEL   983  983  0.0425   9.5710
106   MODEL   461  461  0.8763   9.3715
107   MODEL    10   10  0.0268   8.9005
108   MODEL   462  462  0.2572   8.0654
109   MODEL   870  870  0.2158   7.5325
110   MODEL   981  981  0.1271   7.4972
111   MODEL    58   58  0.0094   7.4627
112   MODEL   982  982  0.0247   7.3864
113   MODEL   483  483  0.0116   7.2289
114   MODEL   883  883  0.0098   7.1429
115   MODEL   809  809  0.0320   6.1404
116   MODEL    57   57  0.0024   5.8824
117   MODEL   882  882  0.1584   5.8407
118   MODEL   426  426  0.0078   5.3571
119   MODEL   880  880  0.4604   4.9619
120   MODEL   881  881  2.2497   3.9245
121   MODEL   806  806  0.0636   3.5242
122   MODEL   898  898  0.1557   3.0603
123   MODEL   850  850  0.0436   2.8939
124   MODEL   884  884  0.5580   2.8127
125   MODEL   808  808  0.0052   2.7027
126   MODEL   804  804  0.0287   2.4390
127   MODEL   997  997  0.2874   0.9264
128   MODEL   890  890  0.0397   0.3534
129   MODEL   732  732  0.0001   0.0000
130   MODEL   908  908  0.0034   0.0000
131   MODEL   466  466  0.0022   0.0000
132   MODEL   805  805  0.0085   0.0000
133   MODEL   598  598  0.0014   0.0000
134   MODEL   902  902  0.0001   0.0000
135   MODEL   731  731  0.0003   0.0000
136   MODEL   599  599  0.0001   0.0000
137   MODEL   904  904  0.0006   0.0000
138   MODEL   474  474  0.0004   0.0000
139   MODEL    60   60  0.0001   0.0000
140   MODEL   427  427  0.0015   0.0000

Remove_Unknowns_in_Feature  MOD_YEAR [9998, 9999] 19387  unknown
    feature = 'MOD_YEAR'
    A = [
        ['0', [1929,1947,1962,1951,1961,1968,1955,1953,1956,1975,1982,1974,1965,1978,1970,1960,1959,1950,1986,1966,1964,1973,1985,1983,1976,1981,1987,1980,1984,1977,1979,1971,1991,1993,1992,1988,1994,1990,1931,1948,1954,1998,1989,1996,1997,2002,1995,2001,2000,1999,2004,]], #  20.7522 %
        ['1', [2003,2005,2006,2007,2020,]], #  19.3813 %
        ['2', [2019,2009,2008,2017,2018,]], #  20.1999 %
        ['3', [2021,2016,1969,1940,2015,]], #  20.7722 %
        ['4', [2013,2014,2022,2012,2011,2010,1967,1972,1957,1952,1928,1932,1933,1963,1958,1934,1930,]], #  18.8937 %
        ['Unknowns', [9998, 9999, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

     Feature  Code  Name     Per      Corr
0   MOD_YEAR  1929  1929  0.0001  100.0000
1   MOD_YEAR  1947  1947  0.0003  100.0000
2   MOD_YEAR  1962  1962  0.0004   66.6667
3   MOD_YEAR  1951  1951  0.0007   60.0000
4   MOD_YEAR  1961  1961  0.0003   50.0000
5   MOD_YEAR  1968  1968  0.0048   48.4848
6   MOD_YEAR  1955  1955  0.0010   42.8571
7   MOD_YEAR  1953  1953  0.0010   42.8571
8   MOD_YEAR  1956  1956  0.0007   40.0000
9   MOD_YEAR  1975  1975  0.0052   38.8889
10  MOD_YEAR  1982  1982  0.0170   37.2881
11  MOD_YEAR  1974  1974  0.0055   36.8421
12  MOD_YEAR  1965  1965  0.0027   36.8421
13  MOD_YEAR  1978  1978  0.0111   33.7662
14  MOD_YEAR  1970  1970  0.0061   33.3333
15  MOD_YEAR  1960  1960  0.0004   33.3333
16  MOD_YEAR  1959  1959  0.0004   33.3333
17  MOD_YEAR  1950  1950  0.0004   33.3333
18  MOD_YEAR  1986  1986  0.0497   33.0435
19  MOD_YEAR  1966  1966  0.0027   31.5789
20  MOD_YEAR  1964  1964  0.0019   30.7692
21  MOD_YEAR  1973  1973  0.0066   30.4348
22  MOD_YEAR  1985  1985  0.0400   30.2158
23  MOD_YEAR  1983  1983  0.0196   30.1471
24  MOD_YEAR  1976  1976  0.0063   29.5455
25  MOD_YEAR  1981  1981  0.0114   29.1139
26  MOD_YEAR  1987  1987  0.0491   27.5660
27  MOD_YEAR  1980  1980  0.0148   26.2136
28  MOD_YEAR  1984  1984  0.0341   25.7384
29  MOD_YEAR  1977  1977  0.0114   25.3165
30  MOD_YEAR  1979  1979  0.0143   25.2525
31  MOD_YEAR  1971  1971  0.0036   24.0000
32  MOD_YEAR  1991  1991  0.1557   23.9593
33  MOD_YEAR  1993  1993  0.2633   22.5383
34  MOD_YEAR  1992  1992  0.1992   21.2581
35  MOD_YEAR  1988  1988  0.0797   20.9765
36  MOD_YEAR  1994  1994  0.4009   20.3737
37  MOD_YEAR  1990  1990  0.1243   20.0463
38  MOD_YEAR  1931  1931  0.0007   20.0000
39  MOD_YEAR  1948  1948  0.0007   20.0000
40  MOD_YEAR  1954  1954  0.0007   20.0000
41  MOD_YEAR  1998  1998  1.1900   19.1381
42  MOD_YEAR  1989  1989  0.1056   18.9632
43  MOD_YEAR  1996  1996  0.6343   18.5782
44  MOD_YEAR  1997  1997  0.9819   18.4859
45  MOD_YEAR  2002  2002  2.8112   18.2680
46  MOD_YEAR  1995  1995  0.5385   18.0310
47  MOD_YEAR  2001  2001  2.3053   17.8966
48  MOD_YEAR  2000  2000  2.0525   17.7990
49  MOD_YEAR  1999  1999  1.5786   17.7587
50  MOD_YEAR  2004  2004  3.7097   17.2414
51  MOD_YEAR  2003  2003  3.2958   17.1598
52  MOD_YEAR  2005  2005  4.1720   17.1472
53  MOD_YEAR  2006  2006  4.4448   16.2405
54  MOD_YEAR  2007  2007  4.7809   16.0691
55  MOD_YEAR  2020  2020  2.2304   15.7463
56  MOD_YEAR  2019  2019  3.7532   15.3988
57  MOD_YEAR  2009  2009  3.0669   15.2513
58  MOD_YEAR  2008  2008  4.4464   14.9776
59  MOD_YEAR  2017  2017  6.8672   14.8623
60  MOD_YEAR  2018  2018  4.8421   14.8157
61  MOD_YEAR  2021  2021  0.9773   14.6963
62  MOD_YEAR  2016  2016  7.5381   14.5543
63  MOD_YEAR  1969  1969  0.0040   14.2857
64  MOD_YEAR  1940  1940  0.0010   14.2857
65  MOD_YEAR  2015  2015  7.4390   14.1867
66  MOD_YEAR  2013  2013  5.7901   14.1389
67  MOD_YEAR  2014  2014  6.3318   14.0579
68  MOD_YEAR  2022  2022  0.0830   13.7153
69  MOD_YEAR  2012  2012  4.9401   13.3701
70  MOD_YEAR  2011  2011  3.9647   13.3057
71  MOD_YEAR  2010  2010  3.5628   13.2662
72  MOD_YEAR  1967  1967  0.0037   11.5385
73  MOD_YEAR  1972  1972  0.0036    4.0000
74  MOD_YEAR  1957  1957  0.0017    0.0000
75  MOD_YEAR  1952  1952  0.0004    0.0000
76  MOD_YEAR  1928  1928  0.0001    0.0000
77  MOD_YEAR  1932  1932  0.0003    0.0000
78  MOD_YEAR  1933  1933  0.0001    0.0000
79  MOD_YEAR  1963  1963  0.0009    0.0000
80  MOD_YEAR  1958  1958  0.0003    0.0000
81  MOD_YEAR  1934  1934  0.0001    0.0000
82  MOD_YEAR  1930  1930  0.0001    0.0000

Remove_Unknowns_in_Feature  MONTH [] 0  unknown
    feature = 'MONTH'
    A = [
        ['0', [7,6,]], #  26.0073 %
        ['1', [8,5,]], #  15.191 %
        ['2', [4,9,3,]], #  26.5887 %
        ['3', [10,2,]], #  14.4245 %
        ['4', [1,11,12,]], #  17.7886 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

   Feature  Code Name     Per     Corr
0    MONTH     7    7  8.5052  16.6255
1    MONTH     6    6  8.3279  16.3584
2    MONTH     8    8  9.1742  15.8942
3    MONTH     5    5  8.0316  15.7038
4    MONTH     4    4  7.1594  15.6224
5    MONTH     9    9  9.0999  15.5111
6    MONTH     3    3  7.5735  14.7533
7    MONTH    10   10  9.9153  14.6625
8    MONTH     2    2  7.0085  14.3631
9    MONTH     1    1  7.4160  14.3448
10   MONTH    11   11  8.9901  14.0935
11   MONTH    12   12  8.7985  13.5785

Remove_Unknowns_in_Feature  NUMOCCS [99] 24156  unknown
    feature = 'NUMOCCS'
    A = [
        ['0', [59,26,35,37,31,13,10,33,8,14,20,27,7,]], #  0.5728 %
        ['1', [2,]], #  24.9571 %
        ['2', [6,]], #  0.8224 %
        ['3', [1,]], #  54.4133 %
        ['4', [11,21,]], #  0.0338 %
        ['5', [3,]], #  10.4153 %
        ['6', [5,38,16,4,12,9,17,19,34,25,28,24,43,49,23,15,29,22,18,40,32,55,53,50,44,51,30,39,41,75,47,95,52,54,62,60,56,58,46,65,57,48,36,45,77,]], #  8.7846 %
        ['Unknowns', [99, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name      Per     Corr
0   NUMOCCS    59   59   0.0010  85.7143
1   NUMOCCS    26   26   0.0051  74.2857
2   NUMOCCS    35   35   0.0023  43.7500
3   NUMOCCS    37   37   0.0016  27.2727
4   NUMOCCS    31   31   0.0022  26.6667
5   NUMOCCS    13   13   0.0088  22.9508
6   NUMOCCS    10   10   0.0273  22.8723
7   NUMOCCS    33   33   0.0015  20.0000
8   NUMOCCS     8    8   0.1562  18.2916
9   NUMOCCS    14   14   0.0138  17.8947
10  NUMOCCS    20   20   0.0017  16.6667
11  NUMOCCS    27   27   0.0017  16.6667
12  NUMOCCS     7    7   0.3496  16.5145
13  NUMOCCS     2    2  24.9571  16.4544
14  NUMOCCS     6    6   0.8224  15.9612
15  NUMOCCS     1    1  54.4133  15.6031
16  NUMOCCS    11   11   0.0309  15.0235
17  NUMOCCS    21   21   0.0029  15.0000
18  NUMOCCS     3    3  10.4153  14.7541
19  NUMOCCS     5    5   2.6919  14.6783
20  NUMOCCS    38   38   0.0010  14.2857
21  NUMOCCS    16   16   0.0062  13.9535
22  NUMOCCS     4    4   5.9609  13.9214
23  NUMOCCS    12   12   0.0212  13.6986
24  NUMOCCS     9    9   0.0577  13.5678
25  NUMOCCS    17   17   0.0039  11.1111
26  NUMOCCS    19   19   0.0026  11.1111
27  NUMOCCS    34   34   0.0010   0.0000
28  NUMOCCS    25   25   0.0010   0.0000
29  NUMOCCS    28   28   0.0013   0.0000
30  NUMOCCS    24   24   0.0012   0.0000
31  NUMOCCS    43   43   0.0004   0.0000
32  NUMOCCS    49   49   0.0009   0.0000
33  NUMOCCS    23   23   0.0009   0.0000
34  NUMOCCS    15   15   0.0084   0.0000
35  NUMOCCS    29   29   0.0016   0.0000
36  NUMOCCS    22   22   0.0022   0.0000
37  NUMOCCS    18   18   0.0025   0.0000
38  NUMOCCS    40   40   0.0006   0.0000
39  NUMOCCS    32   32   0.0012   0.0000
40  NUMOCCS    55   55   0.0003   0.0000
41  NUMOCCS    53   53   0.0001   0.0000
42  NUMOCCS    50   50   0.0004   0.0000
43  NUMOCCS    44   44   0.0003   0.0000
44  NUMOCCS    51   51   0.0001   0.0000
45  NUMOCCS    30   30   0.0004   0.0000
46  NUMOCCS    39   39   0.0006   0.0000
47  NUMOCCS    41   41   0.0004   0.0000
48  NUMOCCS    75   75   0.0109   0.0000
49  NUMOCCS    47   47   0.0001   0.0000
50  NUMOCCS    95   95   0.0001   0.0000
51  NUMOCCS    52   52   0.0003   0.0000
52  NUMOCCS    54   54   0.0004   0.0000
53  NUMOCCS    62   62   0.0001   0.0000
54  NUMOCCS    60   60   0.0001   0.0000
55  NUMOCCS    56   56   0.0001   0.0000
56  NUMOCCS    58   58   0.0003   0.0000
57  NUMOCCS    46   46   0.0001   0.0000
58  NUMOCCS    65   65   0.0001   0.0000
59  NUMOCCS    57   57   0.0001   0.0000
60  NUMOCCS    48   48   0.0004   0.0000
61  NUMOCCS    36   36   0.0001   0.0000
62  NUMOCCS    45   45   0.0001   0.0000
63  NUMOCCS    77   77   0.0001   0.0000

    feature = 'PERMVIT'
    A = [
        ['0', [29,1,21,22,14,20,13,8,15,9,10,7,]], #  14.2472 %
        ['1', [4,]], #  14.3516 %
        ['2', []], #  0.0 %
        ['3', [3,]], #  23.4672 %
        ['4', []], #  9.0994 %
        ['5', [5,6,11,]], #  5.4105 %
        ['6', [2,]], #  33.1765 %
        ['7', [12,24,16,19,18,17,75,]], #  0.2478 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name      Per     Corr
0   PERMVIT    29   29   0.0041  96.5517
1   PERMVIT     1    1   8.6581  28.0313
2   PERMVIT    21   21   0.0029  19.0476
3   PERMVIT    22   22   0.0031  18.1818
4   PERMVIT    14   14   0.0471  17.8571
5   PERMVIT    20   20   0.0140  17.0000
6   PERMVIT    13   13   0.0893  16.9545
7   PERMVIT     8    8   1.4261  16.2146
8   PERMVIT    15   15   0.0441  15.8730
9   PERMVIT     9    9   0.8072  15.1042
10  PERMVIT    10   10   0.4653  14.8494
11  PERMVIT     7    7   2.6859  14.6196
12  PERMVIT     4    4  14.3516  14.3827
13  PERMVIT     3    3  23.4672  14.3120
14  PERMVIT     5    5   9.0994  14.0444
15  PERMVIT     6    6   5.1931  13.9869
16  PERMVIT    11   11   0.2174  13.6041
17  PERMVIT     2    2  33.1765  13.1615
18  PERMVIT    12   12   0.1514  12.6852
19  PERMVIT    24   24   0.0101  12.5000
20  PERMVIT    16   16   0.0336   9.5833
21  PERMVIT    19   19   0.0107   7.8947
22  PERMVIT    18   18   0.0101   6.9444
23  PERMVIT    17   17   0.0214   3.9216
24  PERMVIT    75   75   0.0105   0.0000

    feature = 'PERNOTMVIT'
    A = [
        ['0', [3,2,6,4,7,1,]], #  0.3414 %
        ['1', [0,]], #  99.6555 %
        ['2', [5,]], #  0.0029 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

      Feature  Code Name      Per     Corr
0  PERNOTMVIT     3    3   0.0130  21.5054
1  PERNOTMVIT     2    2   0.0556  20.1511
2  PERNOTMVIT     6    6   0.0007  20.0000
3  PERNOTMVIT     4    4   0.0078  19.6429
4  PERNOTMVIT     7    7   0.0022  18.7500
5  PERNOTMVIT     1    1   0.2621  16.3636
6  PERNOTMVIT     0    0  99.6555  15.1218
7  PERNOTMVIT     5    5   0.0029  14.2857

Remove_Unknowns_in_Feature  PER_TYP [] 0  unknown
    feature = 'PER_TYP'
    A = [
        ['0', [9,]], #  0.0226 %
        ['1', [2,]], #  26.5073 %
        ['2', []], #  0.0 %
        ['3', [1,]], #  73.4701 %
        ['4', []], #  0.0 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

   Feature  Code Name      Per     Corr
0  PER_TYP     9    9   0.0226  21.7391
1  PER_TYP     2    2  26.5073  15.8586
2  PER_TYP     1    1  73.4701  14.8639

    feature = 'PJ'
    A = [
        ['0', [3087,149,147,2904,3069,3292,47,3090,1225,598,2800,610,2705,1645,2412,587,3089,2211,453,2171,2514,2764,2139,2537,1222,1688,1801,2679,4113,1741,2582,2722,189,307,2298,2775,85,172,2330,4047,1223,4144,4056,1362,2793,1231,299,173,96,1684,1634,1070,1838,3224,1750,256,1392,3262,1227,2160,1747,91,1219,1055,4147,2591,308,1802,2735,3106,171,3076,1460,542,2586,86,2513,4107,46,305,1766,1315,565,1308,606,1804,2001,313,1805,1230,3077,2881,1800,3247,718,2286,1692,2883,311,3073,1829,2035,295,839,1709,4135,2592,268,1757,1803,1921,234,4149,1678,2702,1051,618,209,]], #  20.3832 %
        ['1', [4152,2906,2905,2087,1053,2018,260,306,526,4125,1762,2749,4016,250,2607,2972,2292,205,2854,2973,1290,3122,4015,97,359,245,285,2803,970,458,1708,4150,1693,2670,297,4045,2809,261,1197,2811,206,1036,1811,267,1733,455,4151,1714,148,640,1695,2598,4153,161,174,591,625,322,4114,4138,1259,1764,4141,2365,3004,1723,4148,92,2034,2807,1746,3296,315,432,3139,]], #  20.2258 %
        ['2', [4143,2509,232,459,210,892,2851,2857,1041,1763,3119,1265,262,1482,1056,1710,257,1459,2091,1207,437,2808,4055,2136,2682,1114,936,456,87,4142,4145,457,3070,1646,4146,4028,461,1191,893,4012,466,1637,2810,3294,1635,269,516,170,464,45,4139,2799,]], #  19.6773 %
        ['3', [1919,329,967,1736,1724,652,469,1835,1075,321,2907,1571,1208,2792,4019,318,2364,1283,1069,4093,2825,508,1925,1088,4154,4140,2853,123,2763,1374,3010,1040,2759,448,1484,3291,2666,2197,1699,1255,2855,1052,2199,1577,1117,208,966,1920,3202,1573,214,441,3245,3011,211,2782,2152,3131,2797,2819,567,1481,3017,3133,138,440,590,1928,2137,479,137,1366,650,314,460,386,2802,452,1472,3248,309,1628,130,1278,165,900,159,1570,2092,1568,1098,954,896,]], #  19.7326 %
        ['4', [3246,929,721,506,543,1079,2812,1262,1038,965,160,454,500,1050,3019,90,3159,162,1383,972,1260,2151,2717,4136,341,571,505,573,1933,1477,3013,1930,1361,1163,2168,569,336,4137,504,687,1369,1078,163,2748,1247,877,1080,382,517,503,310,2687,338,509,905,2025,641,578,2755,514,3124,568,3253,525,1721,515,1381,362,375,1319,136,334,388,337,378,3200,3201,369,1043,353,3203,360,4036,4029,2411,3209,]], #  19.9813 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code  Name     Per     Corr
0        PJ  3087  3087  0.0041  51.7241
1        PJ   149   149  0.0011  50.0000
2        PJ   147   147  0.0028  45.0000
3        PJ  2904  2904  0.0048  44.1176
4        PJ  3069  3069  0.0352  43.4263
5        PJ  3292  3292  0.0395  42.9078
6        PJ    47    47  0.0762  42.2794
7        PJ  3090  3090  0.0077  40.0000
8        PJ  1225  1225  0.0349  38.9558
9        PJ   598   598  0.0741  38.7524
10       PJ  2800  2800  0.0755  38.2189
11       PJ   610   610  0.1840  38.0046
12       PJ  2705  2705  0.0642  37.5546
13       PJ  1645  1645  0.0938  37.2197
14       PJ  2412  2412  0.0523  36.9973
15       PJ   587   587  0.1598  36.2281
16       PJ  3089  3089  0.0416  35.3535
17       PJ  2211  2211  0.0384  35.0365
18       PJ   453   453  0.2112  34.5056
19       PJ  2171  2171  0.0748  34.0824
20       PJ  2514  2514  0.0790  34.0426
21       PJ  2764  2764  0.1338  33.6126
22       PJ  2139  2139  0.1965  33.5949
23       PJ  2537  2537  0.0409  33.5616
24       PJ  1222  1222  0.0533  33.4211
25       PJ  1688  1688  0.0671  33.4029
26       PJ  1801  1801  0.0017  33.3333
27       PJ  2679  2679  0.1673  33.1658
28       PJ  4113  4113  0.0881  32.7504
29       PJ  1741  1741  0.0565  32.2581
30       PJ  2582  2582  0.2303  32.0146
31       PJ  2722  2722  0.0500  31.3725
32       PJ   189   189  0.1846  30.7517
33       PJ   307   307  0.0483  30.4348
34       PJ  2298  2298  0.1438  30.2144
35       PJ  2775  2775  0.0289  30.0971
36       PJ    85    85  0.2448  29.6508
37       PJ   172   172  0.1281  29.4311
38       PJ  2330  2330  0.1250  29.2601
39       PJ  4047  4047  0.0863  29.0584
40       PJ  1223  1223  0.0465  28.9157
41       PJ  4144  4144  0.6634  28.8973
42       PJ  4056  4056  0.1125  28.7671
43       PJ  1362  1362  0.0234  28.7425
44       PJ  2793  2793  0.5283  28.5676
45       PJ  1231  1231  0.1425  28.3186
46       PJ   299   299  0.3474  27.9952
47       PJ   173   173  0.0893  27.9435
48       PJ    96    96  0.0137  27.5510
49       PJ  1684  1684  0.1275  27.3626
50       PJ  1634  1634  0.0624  27.1910
51       PJ  1070  1070  0.2015  27.1210
52       PJ  1838  1838  0.0879  27.1132
53       PJ  3224  3224  0.0411  26.9625
54       PJ  1750  1750  0.1512  26.8767
55       PJ   256   256  0.2214  26.8354
56       PJ  1392  1392  0.0562  26.4339
57       PJ  3262  3262  0.0398  26.4085
58       PJ  1227  1227  0.1111  26.2295
59       PJ  2160  2160  0.1392  26.1833
60       PJ  1747  1747  0.0813  26.0345
61       PJ    91    91  0.4044  25.8836
62       PJ  1219  1219  0.0043  25.8065
63       PJ  1055  1055  0.2075  25.7934
64       PJ  4147  4147  0.8068  25.6905
65       PJ  2591  2591  0.0890  25.6693
66       PJ   308   308  0.0286  25.4902
67       PJ  1802  1802  0.0874  25.0000
68       PJ  2735  2735  0.0837  24.7906
69       PJ  3106  3106  0.2452  24.7429
70       PJ   171   171  0.0154  24.5455
71       PJ  3076  3076  0.2741  24.5399
72       PJ  1460  1460  0.2908  24.4819
73       PJ   542   542  0.2657  24.4198
74       PJ  2586  2586  0.1477  24.2884
75       PJ    86    86  0.0041  24.1379
76       PJ  2513  2513  0.0353  23.8095
77       PJ  4107  4107  0.0029  23.8095
78       PJ    46    46  0.8138  23.6267
79       PJ   305   305  0.5337  23.6082
80       PJ  1766  1766  0.0823  23.3390
81       PJ  1315  1315  0.1083  23.2859
82       PJ   565   565  0.3328  23.2421
83       PJ  1308  1308  0.0894  23.1975
84       PJ   606   606  0.1092  23.1065
85       PJ  1804  1804  0.0601  23.0769
86       PJ  2001  2001  0.1078  23.0169
87       PJ   313   313  0.2022  23.0076
88       PJ  1805  1805  0.0420  23.0000
89       PJ  1230  1230  0.1048  22.9947
90       PJ  3077  3077  0.1050  22.9640
91       PJ  2881  2881  0.1162  22.9192
92       PJ  1800  1800  1.4170  22.9057
93       PJ  3247  3247  0.1330  22.7608
94       PJ   718   718  0.0593  22.6950
95       PJ  2286  2286  0.2632  22.5240
96       PJ  1692  1692  0.1197  22.4824
97       PJ  2883  2883  0.0765  22.3443
98       PJ   311   311  0.0170  22.3140
99       PJ  3073  3073  0.0240  22.2222
100      PJ  1829  1829  0.2000  22.1444
101      PJ  2035  2035  0.3735  22.1013
102      PJ   295   295  0.5209  22.0608
103      PJ   839   839  0.0942  22.0238
104      PJ  1709  1709  0.4522  21.4751
105      PJ  4135  4135  1.1818  21.2261
106      PJ  2592  2592  0.0291  21.1538
107      PJ   268   268  0.1107  21.1392
108      PJ  1757  1757  0.2010  21.1297
109      PJ  1803  1803  0.0769  21.1293
110      PJ  1921  1921  0.2197  21.1097
111      PJ   234   234  0.2028  20.9399
112      PJ  4149  4149  0.1683  20.8993
113      PJ  1678  1678  0.1061  20.8719
114      PJ  2702  2702  0.3935  20.6909
115      PJ  1051  1051  0.0041  20.6897
116      PJ   618   618  0.2930  20.6600
117      PJ   209   209  0.0299  20.6573
118      PJ  4152  4152  1.0974  20.4572
119      PJ  2906  2906  0.0702  20.3593
120      PJ  2905  2905  0.0172  20.3252
121      PJ  2087  2087  0.3055  20.2294
122      PJ  1053  1053  2.6320  20.2279
123      PJ  2018  2018  0.2279  20.1107
124      PJ   260   260  0.2018  20.0694
125      PJ   306   306  0.1805  20.0311
126      PJ   526   526  0.6864  20.0082
127      PJ  4125  4125  0.0028  20.0000
128      PJ  1762  1762  0.0500  19.8880
129      PJ  2749  2749  0.0114  19.7531
130      PJ  4016  4016  0.0547  19.7436
131      PJ   250   250  0.1289  19.5652
132      PJ  2607  2607  0.0057  19.5122
133      PJ  2972  2972  0.0240  19.2982
134      PJ  2292  2292  0.1570  19.2857
135      PJ   205   205  0.2574  19.2705
136      PJ  2854  2854  0.0656  19.2308
137      PJ  2973  2973  0.0074  18.8679
138      PJ  1290  1290  0.1156  18.7879
139      PJ  3122  3122  0.0276  18.7817
140      PJ  4015  4015  0.0898  18.7207
141      PJ    97    97  0.0143  18.6275
142      PJ   359   359  0.0060  18.6047
143      PJ   245   245  0.1734  18.5934
144      PJ   285   285  0.1169  18.5851
145      PJ  2803  2803  0.1253  18.5682
146      PJ   970   970  0.4550  18.2938
147      PJ   458   458  0.0399  18.2456
148      PJ  1708  1708  0.3533  18.0881
149      PJ  4150  4150  1.0389  18.0359
150      PJ  1693  1693  0.1065  18.0263
151      PJ  2670  2670  0.6539  17.9811
152      PJ   297   297  0.0682  17.8645
153      PJ  4045  4045  0.0039  17.8571
154      PJ  2809  2809  0.0220  17.8344
155      PJ   261   261  0.3171  17.6757
156      PJ  1197  1197  0.0294  17.6190
157      PJ  2811  2811  0.0493  17.6136
158      PJ   206   206  0.6835  17.5723
159      PJ  1036  1036  0.1288  17.5190
160      PJ  1811  1811  0.0177  17.4603
161      PJ   267   267  0.0249  17.4157
162      PJ  1733  1733  0.0259  17.2973
163      PJ   455   455  0.6854  17.1131
164      PJ  4151  4151  0.4655  17.0981
165      PJ  1714  1714  0.2192  17.0716
166      PJ   148   148  0.0066  17.0213
167      PJ   640   640  0.0412  17.0068
168      PJ  1695  1695  0.1254  16.9832
169      PJ  2598  2598  0.0711  16.9625
170      PJ  4153  4153  0.5439  16.9544
171      PJ   161   161  0.2416  16.8794
172      PJ   174   174  0.0457  16.8712
173      PJ   591   591  0.2989  16.8308
174      PJ   625   625  0.0667  16.8067
175      PJ   322   322  0.1315  16.7377
176      PJ  4114  4114  0.0008  16.6667
177      PJ  4138  4138  1.0532  16.6068
178      PJ  1259  1259  0.0467  16.5165
179      PJ  1764  1764  0.0936  16.4671
180      PJ  4141  4141  1.1567  16.2103
181      PJ  2365  2365  0.0917  16.2080
182      PJ  3004  3004  0.2259  16.1911
183      PJ  1723  1723  1.2607  16.1850
184      PJ  4148  4148  1.4999  16.1637
185      PJ    92    92  0.0590  16.1520
186      PJ  2034  2034  0.1485  16.1321
187      PJ  2807  2807  0.0245  16.0000
188      PJ  1746  1746  0.2132  15.9763
189      PJ  3296  3296  0.4769  15.8977
190      PJ   315   315  0.0238  15.8824
191      PJ   432   432  0.2402  15.8693
192      PJ  3139  3139  0.0460  15.8537
193      PJ  4143  4143  0.8483  15.7277
194      PJ  2509  2509  0.0366  15.7088
195      PJ   232   232  0.2296  15.6899
196      PJ   459   459  0.0179  15.6250
197      PJ   210   210  0.1785  15.6201
198      PJ   892   892  0.3529  15.5679
199      PJ  2851  2851  0.5318  15.5468
200      PJ  2857  2857  0.1002  15.5245
201      PJ  1041  1041  0.0272  15.4639
202      PJ  1763  1763  0.0426  15.4605
203      PJ  3119  3119  0.0563  15.4229
204      PJ  1265  1265  0.0384  15.3285
205      PJ   262   262  0.3083  15.2727
206      PJ  1482  1482  0.5470  15.2703
207      PJ  1056  1056  0.1847  15.2504
208      PJ  1710  1710  0.2964  15.1773
209      PJ   257   257  0.2825  15.1290
210      PJ  1459  1459  0.1860  15.0716
211      PJ  2091  2091  0.5164  15.0611
212      PJ  1207  1207  0.1628  14.9742
213      PJ   437   437  0.4625  14.9091
214      PJ  2808  2808  0.0226  14.9068
215      PJ  4055  4055  0.2635  14.8936
216      PJ  2136  2136  0.1460  14.8752
217      PJ  2682  2682  0.1785  14.8352
218      PJ  1114  1114  0.1993  14.7679
219      PJ   936   936  0.1177  14.7619
220      PJ   456   456  0.5655  14.6468
221      PJ    87    87  1.5738  14.6215
222      PJ  4142  4142  1.9118  14.5946
223      PJ  4145  4145  1.1440  14.5902
224      PJ   457   457  0.5639  14.5378
225      PJ  3070  3070  0.0174  14.5161
226      PJ  1646  1646  0.0767  14.4424
227      PJ  4146  4146  1.1734  14.4154
228      PJ  4028  4028  0.0432  14.2857
229      PJ   461   461  0.0020  14.2857
230      PJ  1191  1191  0.1759  14.2629
231      PJ   893   893  0.4309  14.1463
232      PJ  4012  4012  0.0645  14.1304
233      PJ   466   466  0.2918  14.1210
234      PJ  1637  1637  0.1163  14.0964
235      PJ  2810  2810  0.7122  13.9906
236      PJ  3294  3294  0.0692  13.9676
237      PJ  1635  1635  0.0746  13.9098
238      PJ   269   269  0.0101  13.8889
239      PJ   516   516  0.6682  13.8423
240      PJ   170   170  0.4050  13.8408
241      PJ   464   464  0.1427  13.7525
242      PJ    45    45  0.0245  13.7143
243      PJ  4139  4139  1.7672  13.5052
244      PJ  2799  2799  0.3850  13.4692
245      PJ  1919  1919  1.7813  13.4057
246      PJ   329   329  0.0408  13.4021
247      PJ   967   967  0.0472  13.3531
248      PJ  1736  1736  0.1125  13.3250
249      PJ  1724  1724  0.2424  13.2948
250      PJ   652   652  0.0561  13.2500
251      PJ   469   469  0.1408  13.2338
252      PJ  1835  1835  0.1017  13.2231
253      PJ  1075  1075  0.1301  13.1466
254      PJ   321   321  0.0085  13.1148
255      PJ  2907  2907  0.5421  13.1075
256      PJ  1571  1571  0.1329  13.0802
257      PJ  1208  1208  0.0903  13.0435
258      PJ  2792  2792  0.0938  13.0045
259      PJ  4019  4019  0.0367  12.9771
260      PJ   318   318  0.0486  12.9683
261      PJ  2364  2364  0.0465  12.9518
262      PJ  1283  1283  0.1756  12.9290
263      PJ  1069  1069  0.2022  12.8898
264      PJ  4093  4093  0.1087  12.8866
265      PJ  2825  2825  0.0621  12.8668
266      PJ   508   508  0.2147  12.7937
267      PJ  1925  1925  0.1902  12.7487
268      PJ  1088  1088  0.0919  12.6524
269      PJ  4154  4154  0.2478  12.6131
270      PJ  4140  4140  0.6654  12.4052
271      PJ  2853  2853  0.1089  12.3552
272      PJ   123   123  0.0114  12.3457
273      PJ  2763  2763  0.1261  12.3333
274      PJ  1374  1374  0.1909  12.2614
275      PJ  3010  3010  0.0687  12.2449
276      PJ  1040  1040  0.1278  12.1711
277      PJ  2759  2759  0.1038  12.1457
278      PJ   448   448  0.1826  12.1259
279      PJ  1484  1484  1.5282  12.1229
280      PJ  3291  3291  0.0046  12.1212
281      PJ  2666  2666  0.2695  12.1165
282      PJ  2197  2197  0.1135  12.0988
283      PJ  1699  1699  0.1543  12.0799
284      PJ  1255  1255  0.0371  12.0755
285      PJ  2855  2855  0.0987  12.0739
286      PJ  1052  1052  0.0199  11.9718
287      PJ  2199  2199  0.0925  11.9697
288      PJ  1577  1577  0.0835  11.9128
289      PJ  1117  1117  0.2200  11.9108
290      PJ   208   208  0.2095  11.9064
291      PJ   966   966  0.7157  11.7290
292      PJ  1920  1920  0.0576  11.6788
293      PJ  3202  3202  0.0697  11.6700
294      PJ  1573  1573  0.1647  11.6596
295      PJ   214   214  0.4081  11.6415
296      PJ   441   441  0.2007  11.5922
297      PJ  3245  3245  0.0757  11.4815
298      PJ  3011  3011  0.0404  11.4583
299      PJ   211   211  0.2531  11.4064
300      PJ  2782  2782  0.1068  11.2861
301      PJ  2152  2152  0.6522  11.2376
302      PJ  3131  3131  0.0437  11.2179
303      PJ  2797  2797  0.2364  11.2033
304      PJ  2819  2819  0.1785  11.1460
305      PJ   567   567  0.2335  11.1044
306      PJ  1481  1481  0.1347  11.0302
307      PJ  3017  3017  0.0115  10.9756
308      PJ  3133  3133  0.0767  10.9689
309      PJ   138   138  1.7717  10.7578
310      PJ   440   440  0.2284  10.7362
311      PJ   590   590  0.1575  10.6762
312      PJ  1928  1928  0.1347  10.6139
313      PJ  2137  2137  0.0212  10.5960
314      PJ   479   479  0.0425  10.5611
315      PJ   137   137  0.4478  10.3599
316      PJ  1366  1366  0.2722  10.3502
317      PJ   650   650  0.0853  10.3448
318      PJ   314   314  0.0353  10.3175
319      PJ   460   460  0.0055  10.2564
320      PJ   386   386  0.0820  10.2564
321      PJ  2802  2802  0.3024  10.2410
322      PJ   452   452  0.0247  10.2273
323      PJ  1472  1472  0.2010  10.1813
324      PJ  3248  3248  0.4064  10.1724
325      PJ   309   309  0.0042  10.0000
326      PJ  1628  1628  0.0764   9.9083
327      PJ   130   130  0.0269   9.8958
328      PJ  1278  1278  0.1375   9.8879
329      PJ   165   165  0.2567   9.8253
330      PJ   900   900  0.4259   9.7730
331      PJ   159   159  0.8958   9.7153
332      PJ  1570  1570  0.1780   9.6850
333      PJ  2092  2092  0.3197   9.6011
334      PJ  1568  1568  0.2090   9.5909
335      PJ  1098  1098  1.1912   9.5412
336      PJ   954   954  0.1581   9.3972
337      PJ   896   896  0.3138   9.3345
338      PJ  3246  3246  0.0800   9.2820
339      PJ   929   929  0.0604   9.2807
340      PJ   721   721  0.1589   9.2593
341      PJ   506   506  0.3757   9.2503
342      PJ   543   543  0.3970   9.2128
343      PJ  1079  1079  0.3959   9.2035
344      PJ  2812  2812  0.0094   8.9552
345      PJ  1262  1262  0.0363   8.8803
346      PJ  1038  1038  0.0111   8.8608
347      PJ   965   965  0.0112   8.7500
348      PJ   160   160  0.7060   8.6741
349      PJ   454   454  0.2223   8.6381
350      PJ   500   500  0.2160   8.6308
351      PJ  1050  1050  0.1113   8.5642
352      PJ  3019  3019  0.1549   8.4163
353      PJ    90    90  0.2322   8.3887
354      PJ  3159  3159  0.0310   8.1448
355      PJ   162   162  0.2661   8.1095
356      PJ  1383  1383  0.0698   8.0321
357      PJ   972   972  0.6123   8.0110
358      PJ  1260  1260  0.0531   7.9156
359      PJ  2151  2151  0.0053   7.8947
360      PJ  2717  2717  0.0820   7.8632
361      PJ  4136  4136  0.4417   7.8363
362      PJ   341   341  0.0304   7.8341
363      PJ   571   571  0.2047   7.8029
364      PJ   505   505  0.3292   7.7905
365      PJ   573   573  3.3815   7.5967
366      PJ  1933  1933  0.2213   7.4731
367      PJ  1477  1477  0.2961   7.4302
368      PJ  3013  3013  0.0975   7.3276
369      PJ  1930  1930  0.1364   7.2970
370      PJ  1361  1361  0.4472   7.1451
371      PJ  1163  1163  0.2040   7.1429
372      PJ  2168  2168  0.0984   7.1225
373      PJ   569   569  0.3349   7.0293
374      PJ   336   336  0.4154   6.9163
375      PJ  4137  4137  1.4059   6.8481
376      PJ   504   504  0.2056   6.8166
377      PJ   687   687  0.0901   6.6874
378      PJ  1369  1369  0.0810   6.5744
379      PJ  1078  1078  0.4539   6.4835
380      PJ   163   163  0.2339   6.3511
381      PJ  2748  2748  0.0601   6.2937
382      PJ  1247  1247  0.0405   6.2284
383      PJ   877   877  0.2204   6.1666
384      PJ  1080  1080  0.1491   6.0150
385      PJ   382   382  0.0140   6.0000
386      PJ   517   517  0.5281   5.9448
387      PJ   503   503  0.2171   5.9393
388      PJ   310   310  0.0048   5.8824
389      PJ  2687  2687  0.0652   5.5914
390      PJ   338   338  0.2940   5.4337
391      PJ   509   509  0.2018   5.4167
392      PJ   905   905  0.1184   5.3254
393      PJ  2025  2025  0.0750   5.2336
394      PJ   641   641  0.2338   5.0959
395      PJ   578   578  0.3551   5.0513
396      PJ  2755  2755  0.2172   5.0323
397      PJ   514   514  0.2161   4.9935
398      PJ  3124  3124  0.0255   4.9451
399      PJ   568   568  0.2405   4.8951
400      PJ  3253  3253  0.0092   4.5455
401      PJ   525   525  0.0907   4.4822
402      PJ  1721  1721  0.0733   4.3977
403      PJ   515   515  0.2270   3.9506
404      PJ  1381  1381  0.0792   3.5398
405      PJ   362   362  0.7322   3.3876
406      PJ   375   375  0.0252   3.3333
407      PJ  1319  1319  0.0336   3.3333
408      PJ   136   136  0.0612   3.2037
409      PJ   334   334  0.1338   3.0366
410      PJ   388   388  0.6706   3.0303
411      PJ   337   337  0.5401   2.8801
412      PJ   378   378  0.0196   2.8571
413      PJ  3200  3200  0.2132   2.5641
414      PJ  3201  3201  0.1103   1.9060
415      PJ   369   369  0.0757   1.8519
416      PJ  1043  1043  0.0269   1.5625
417      PJ   353   353  0.2308   1.4572
418      PJ  3203  3203  0.0188   0.7463
419      PJ   360   360  0.0003   0.0000
420      PJ  4036  4036  0.0003   0.0000
421      PJ  4029  4029  0.0006   0.0000
422      PJ  2411  2411  0.0013   0.0000
423      PJ  3209  3209  0.0034   0.0000

    feature = 'PSU'
    A = [
        ['0', [15,75,57,40,52,64,76,80,34,68,66,50,60,24,63,17,55,]], #  20.6357 %
        ['1', [47,62,53,10,49,30,48,82,35,31,25,72,]], #  20.5044 %
        ['2', [65,56,32,45,83,78,67,12,22,]], #  19.1893 %
        ['3', [58,14,26,70,28,33,81,13,77,20,29,54,61,]], #  21.1101 %
        ['4', [27,39,41,51,59,38,37,46,44,]], #  18.5605 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

   Feature  Code Name     Per     Corr
0      PSU    15   15  0.2454  30.2113
1      PSU    75   75  1.2499  28.8261
2      PSU    57   57  0.5729  26.4922
3      PSU    40   40  1.5638  25.7640
4      PSU    52   52  0.9094  24.2102
5      PSU    64   64  0.8170  23.0875
6      PSU    76   76  0.8271  23.0261
7      PSU    80   80  1.7029  22.8952
8      PSU    34   34  0.6524  22.5134
9      PSU    68   68  1.4294  22.2255
10     PSU    66   66  0.6207  21.6302
11     PSU    50   50  0.5000  19.4507
12     PSU    60   60  1.2386  19.2238
13     PSU    24   24  0.6940  19.1842
14     PSU    63   63  1.9959  19.0844
15     PSU    17   17  3.0890  19.0636
16     PSU    55   55  1.0180  18.7775
17     PSU    47   47  1.5093  18.7187
18     PSU    62   62  1.5962  18.4197
19     PSU    53   53  1.7279  18.3617
20     PSU    10   10  0.5009  18.0190
21     PSU    49   49  1.0527  17.8781
22     PSU    30   30  0.9354  17.5581
23     PSU    48   48  2.5464  17.4298
24     PSU    82   82  1.0868  17.2921
25     PSU    35   35  2.6826  17.2030
26     PSU    31   31  1.5487  17.1297
27     PSU    25   25  2.6833  16.8329
28     PSU    72   72  1.9925  16.5213
29     PSU    65   65  2.1510  16.4962
30     PSU    56   56  2.2046  16.4135
31     PSU    32   32  2.0140  16.0184
32     PSU    45   45  0.7038  15.8104
33     PSU    83   83  2.3688  15.6836
34     PSU    78   78  2.2107  15.5563
35     PSU    67   67  3.8386  15.1473
36     PSU    12   12  3.7949  15.0929
37     PSU    22   22  0.4204  15.0333
38     PSU    58   58  1.6335  14.8850
39     PSU    14   14  0.6053  14.6562
40     PSU    26   26  0.4908  14.6488
41     PSU    70   70  3.2335  14.5625
42     PSU    28   28  3.1903  13.4680
43     PSU    33   33  3.1837  13.3595
44     PSU    81   81  0.2758  12.9573
45     PSU    13   13  0.7171  12.8005
46     PSU    77   77  1.0387  12.7091
47     PSU    20   20  1.2642  12.1494
48     PSU    29   29  1.9995  11.9218
49     PSU    54   54  2.4165  11.7961
50     PSU    61   61  0.8324  11.1616
51     PSU    27   27  1.8623  11.0994
52     PSU    39   39  1.4676  10.2273
53     PSU    41   41  2.6002   9.6421
54     PSU    51   51  2.6094   9.3555
55     PSU    59   59  2.7919   7.4039
56     PSU    38   38  4.9333   7.3888
57     PSU    37   37  0.8879   5.9659
58     PSU    46   46  2.3186   3.9770
59     PSU    44   44  0.9516   3.7997

    feature = 'PVH_INVL'
    A = [
        ['0', [10,12,7,8,4,5,9,3,6,2,]], #  0.4125 %
        ['1', [0,]], #  97.5149 %
        ['2', [1,]], #  2.0727 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

     Feature  Code Name      Per      Corr
0   PVH_INVL    10   10   0.0001  100.0000
1   PVH_INVL    12   12   0.0003  100.0000
2   PVH_INVL     7    7   0.0013   77.7778
3   PVH_INVL     8    8   0.0003   50.0000
4   PVH_INVL     4    4   0.0255   37.9121
5   PVH_INVL     5    5   0.0070   36.0000
6   PVH_INVL     9    9   0.0004   33.3333
7   PVH_INVL     3    3   0.0816   32.3024
8   PVH_INVL     6    6   0.0034   29.1667
9   PVH_INVL     2    2   0.2926   27.2989
10  PVH_INVL     0    0  97.5149   15.0835
11  PVH_INVL     1    1   2.0727   14.4422

    feature = 'REGION'
    A = [
        ['0', []], #  0.0 %
        ['1', [1,]], #  10.9083 %
        ['2', []], #  0.0 %
        ['3', [3,]], #  55.2993 %
        ['4', []], #  0.0 %
        ['5', [2,]], #  17.8327 %
        ['6', []], #  0.0 %
        ['7', [4,]], #  15.9597 %
        ['8', []], #  0.0 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

  Feature  Code Name      Per     Corr
0  REGION     1    1  10.9083  18.9098
1  REGION     3    3  55.2993  15.1991
2  REGION     2    2  17.8327  14.3436
3  REGION     4    4  15.9597  13.1802

    feature = 'RELJCT1'
    A = [
        ['0', []], #  0.0 %
        ['1', [0,]], #  74.3341 %
        ['2', []], #  0.0 %
        ['3', [8,]], #  21.458 %
        ['4', [1,9,]], #  4.2079 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

   Feature  Code Name      Per     Corr
0  RELJCT1     0    0  74.3341  15.2418
1  RELJCT1     8    8  21.4580  14.8344
2  RELJCT1     1    1   4.1716  14.7008
3  RELJCT1     9    9   0.0363   7.7220

Remove_Unknowns_in_Feature  RELJCT2 [98, 99] 42273  unknown
    feature = 'RELJCT2'
    A = [
        ['0', [19,6,5,]], #  1.2531 %
        ['1', [2,]], #  28.3024 %
        ['2', [16,]], #  0.0027 %
        ['3', [1,]], #  36.8757 %
        ['4', [7,8,18,17,]], #  9.2455 %
        ['5', [3,]], #  22.6171 %
        ['6', [4,20,]], #  1.7036 %
        ['Unknowns', [98, 99, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name      Per     Corr
0   RELJCT2    19   19   0.2395  34.3284
1   RELJCT2     6    6   0.0705  20.2960
2   RELJCT2     5    5   0.9431  19.4440
3   RELJCT2     2    2  28.3024  18.7445
4   RELJCT2    16   16   0.0027  16.6667
5   RELJCT2     1    1  36.8757  16.6403
6   RELJCT2     7    7   0.1861  14.7318
7   RELJCT2     8    8   7.4513  12.9268
8   RELJCT2    18   18   1.5290  11.7498
9   RELJCT2    17   17   0.0791  10.1695
10  RELJCT2     3    3  22.6171   8.9259
11  RELJCT2     4    4   0.6391   8.5781
12  RELJCT2    20   20   1.0645   7.4587

Remove_Unknowns_in_Feature  REL_ROAD [98, 99] 222  unknown
    feature = 'REL_ROAD'
    A = [
        ['0', [10,8,4,6,3,12,5,2,]], #  9.9969 %
        ['1', [1,]], #  88.4404 %
        ['2', [11,7,]], #  1.5626 %
        ['Unknowns', [98, 99, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

     Feature  Code Name      Per     Corr
0   REL_ROAD    10   10   0.0182  42.3077
1   REL_ROAD     8    8   0.1036  38.1597
2   REL_ROAD     4    4   7.4926  35.6646
3   REL_ROAD     6    6   0.1333  32.3870
4   REL_ROAD     3    3   1.4766  31.1023
5   REL_ROAD    12   12   0.0199  30.2817
6   REL_ROAD     5    5   0.4449  29.3006
7   REL_ROAD     2    2   0.3078  23.2696
8   REL_ROAD     1    1  88.4404  13.0393
9   REL_ROAD    11   11   0.1086  12.9032
10  REL_ROAD     7    7   1.4540  10.3934

    feature = 'SCH_BUS'
    A = [
        ['0', []], #  0.0 %
        ['1', [0,]], #  99.5024 %
        ['2', [1,]], #  0.4976 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

   Feature  Code Name      Per     Corr
0  SCH_BUS     0    0  99.5024  15.1521
1  SCH_BUS     1    1   0.4976  10.5322

    feature = 'SEX'
    A = [
        ['0', []], #  0.0 %
        ['1', [2,]], #  43.8701 %
        ['2', []], #  0.0 %
        ['3', [1,]], #  52.3111 %
        ['4', [8,9,]], #  3.8188 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

  Feature  Code Name      Per     Corr
0     SEX     2    2  43.8701  16.7236
1     SEX     1    1  52.3111  14.7688
2     SEX     8    8   2.4230   2.3771
3     SEX     9    9   1.3958   0.6526

Remove_Unknowns_in_Feature  TYP_INT [98, 99] 74693  unknown
    feature = 'TYP_INT'
    A = [
        ['0', [11,]], #  0.0045 %
        ['1', [1,]], #  57.3325 %
        ['2', [10,]], #  0.0388 %
        ['3', [3,]], #  11.9265 %
        ['4', [4,]], #  0.3267 %
        ['5', [2,]], #  29.8771 %
        ['6', [7,6,5,]], #  0.4939 %
        ['Unknowns', [98, 99, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

   Feature  Code Name      Per     Corr
0  TYP_INT    11   11   0.0045  17.2414
1  TYP_INT     1    1  57.3325  15.8711
2  TYP_INT    10   10   0.0388  15.7258
3  TYP_INT     3    3  11.9265  15.7044
4  TYP_INT     4    4   0.3267  15.6684
5  TYP_INT     2    2  29.8771  15.3884
6  TYP_INT     7    7   0.2212  15.2866
7  TYP_INT     6    6   0.2077   8.2894
8  TYP_INT     5    5   0.0650   6.9880

    feature = 'URBANICITY'
    A = [
        ['0', []], #  0.0 %
        ['1', [2,]], #  22.6908 %
        ['2', []], #  0.0 %
        ['3', [1,]], #  77.3092 %
        ['4', []], #  0.0 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

      Feature  Code Name      Per     Corr
0  URBANICITY     2    2  22.6908  16.5730
1  URBANICITY     1    1  77.3092  14.7053

Remove_Unknowns_in_Feature  VALIGN [8, 9] 43563  unknown
    feature = 'VALIGN'
    A = [
        ['0', [3,2,4,]], #  8.513 %
        ['1', [1,]], #  88.9692 %
        ['2', [0,]], #  2.5179 %
        ['Unknowns', [8, 9, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

  Feature  Code Name      Per     Corr
0  VALIGN     3    3   3.4009  29.1451
1  VALIGN     2    2   3.7663  21.4710
2  VALIGN     4    4   1.3458  17.9772
3  VALIGN     1    1  88.9692  14.5658
4  VALIGN     0    0   2.5179   8.5418

    feature = 'VE_FORMS'
    A = [
        ['0', [10,]], #  0.0059 %
        ['1', [1,]], #  13.723 %
        ['2', [9,8,13,15,7,6,5,4,]], #  3.651 %
        ['3', [3,]], #  11.0684 %
        ['4', []], #  0.0 %
        ['5', [2,]], #  71.5442 %
        ['6', [11,12,]], #  0.0076 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

     Feature  Code Name      Per     Corr
0   VE_FORMS    10   10   0.0059  38.0952
1   VE_FORMS     1    1  13.7230  28.4193
2   VE_FORMS     9    9   0.0171  24.5902
3   VE_FORMS     8    8   0.0303  21.7593
4   VE_FORMS    13   13   0.0021  20.0000
5   VE_FORMS    15   15   0.0063  20.0000
6   VE_FORMS     7    7   0.0670  18.8285
7   VE_FORMS     6    6   0.1857  18.6415
8   VE_FORMS     5    5   0.6577  16.8123
9   VE_FORMS     4    4   2.6848  15.2991
10  VE_FORMS     3    3  11.0684  14.8835
11  VE_FORMS     2    2  71.5442  12.5767
12  VE_FORMS    11   11   0.0056  10.0000
13  VE_FORMS    12   12   0.0020   0.0000

    feature = 'VE_TOTAL'
    A = [
        ['0', [10,]], #  0.0071 %
        ['1', [1,]], #  11.763 %
        ['2', [13,8,9,6,7,15,5,4,]], #  3.8895 %
        ['3', [3,]], #  11.5525 %
        ['4', [11,]], #  0.0062 %
        ['5', [2,]], #  72.7797 %
        ['6', [12,]], #  0.002 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

     Feature  Code Name      Per     Corr
0   VE_TOTAL    10   10   0.0071  37.2549
1   VE_TOTAL     1    1  11.7630  30.9196
2   VE_TOTAL    13   13   0.0024  29.4118
3   VE_TOTAL     8    8   0.0359  24.6094
4   VE_TOTAL     9    9   0.0164  23.9316
5   VE_TOTAL     6    6   0.2063  21.3315
6   VE_TOTAL     7    7   0.0769  20.9472
7   VE_TOTAL    15   15   0.0063  20.0000
8   VE_TOTAL     5    5   0.7083  17.9660
9   VE_TOTAL     4    4   2.8370  16.1381
10  VE_TOTAL     3    3  11.5525  15.3563
11  VE_TOTAL    11   11   0.0062  13.6364
12  VE_TOTAL     2    2  72.7797  12.4410
13  VE_TOTAL    12   12   0.0020   0.0000

Remove_Unknowns_in_Feature  VNUM_LAN [8, 9] 192305  unknown
    feature = 'VNUM_LAN'
    A = [
        ['0', []], #  0.0 %
        ['1', [2,]], #  44.5157 %
        ['2', []], #  0.0 %
        ['3', [4,]], #  14.9317 %
        ['4', []], #  0.0 %
        ['5', [3,]], #  18.4957 %
        ['6', []], #  0.0 %
        ['7', [5,]], #  11.2134 %
        ['8', [7,1,6,0,]], #  10.8435 %
        ['Unknowns', [8, 9, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name      Per     Corr
0  VNUM_LAN     2    2  44.5157  19.1318
1  VNUM_LAN     4    4  14.9317  14.2742
2  VNUM_LAN     3    3  18.4957  13.8262
3  VNUM_LAN     5    5  11.2134  13.7448
4  VNUM_LAN     7    7   1.4350  12.5936
5  VNUM_LAN     1    1   2.4262  11.6391
6  VNUM_LAN     6    6   3.7459  11.2414
7  VNUM_LAN     0    0   3.2364   8.5418

Remove_Unknowns_in_Feature  VPROFILE [8, 9] 96835  unknown
    feature = 'VPROFILE'
    A = [
        ['0', [6,4,5,3,2,]], #  14.2509 %
        ['1', [1,]], #  83.0137 %
        ['2', [0,]], #  2.7354 %
        ['Unknowns', [8, 9, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name      Per     Corr
0  VPROFILE     6    6   2.6245  22.9890
1  VPROFILE     4    4   0.1741  21.6946
2  VPROFILE     5    5   1.9676  21.3597
3  VPROFILE     3    3   1.2633  20.7547
4  VPROFILE     2    2   8.2214  15.0560
5  VPROFILE     1    1  83.0137  15.0114
6  VPROFILE     0    0   2.7354   8.5418

Remove_Unknowns_in_Feature  VSPD_LIM [98, 99] 92357  unknown
    feature = 'VSPD_LIM'
    A = [
        ['0', [90,]], #  0.0002 %
        ['1', [55,]], #  11.1874 %
        ['2', [75,80,50,]], #  9.3987 %
        ['3', [70,65,]], #  5.8534 %
        ['4', [45,]], #  21.9134 %
        ['5', [60,]], #  2.0159 %
        ['6', [40,]], #  11.3393 %
        ['7', []], #  0.0 %
        ['8', [35,]], #  18.9864 %
        ['9', [25,30,20,0,15,5,10,]], #  19.3055 %
        ['Unknowns', [98, 99, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

     Feature  Code Name      Per      Corr
0   VSPD_LIM    90   90   0.0002  100.0000
1   VSPD_LIM    55   55  11.1874   21.7563
2   VSPD_LIM    75   75   0.3403   19.9149
3   VSPD_LIM    80   80   0.1354   19.7384
4   VSPD_LIM    50   50   3.6373   18.3403
5   VSPD_LIM    70   70   5.2857   17.6610
6   VSPD_LIM    65   65   5.8534   16.4347
7   VSPD_LIM    45   45  21.9134   15.1027
8   VSPD_LIM    60   60   2.0159   14.6131
9   VSPD_LIM    40   40  11.3393   13.8911
10  VSPD_LIM    35   35  18.9864   13.7623
11  VSPD_LIM    25   25   8.5860   12.2317
12  VSPD_LIM    30   30   6.5930   11.3195
13  VSPD_LIM    20   20   0.6169   10.0992
14  VSPD_LIM     0    0   2.7545    8.5676
15  VSPD_LIM    15   15   0.5222    8.3539
16  VSPD_LIM     5    5   0.0647    6.7164
17  VSPD_LIM    10   10   0.1682    6.2201

Remove_Unknowns_in_Feature  VSURCOND [98, 99] 25039  unknown
    feature = 'VSURCOND'
    A = [
        ['0', [5,11,7,8,6,]], #  0.2858 %
        ['1', [1,]], #  81.8341 %
        ['2', []], #  0.0 %
        ['3', [2,]], #  13.44 %
        ['4', [10,4,3,0,]], #  4.4401 %
        ['Unknowns', [98, 99, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

     Feature  Code Name      Per     Corr
0   VSURCOND     5    5   0.0084  37.9310
1   VSURCOND    11   11   0.1057  25.8242
2   VSURCOND     7    7   0.0062  23.2558
3   VSURCOND     8    8   0.0298  20.4878
4   VSURCOND     6    6   0.1357  15.8458
5   VSURCOND     1    1  81.8341  15.4078
6   VSURCOND     2    2  13.4400  15.0684
7   VSURCOND    10   10   0.1728  14.0336
8   VSURCOND     4    4   0.7920  13.6439
9   VSURCOND     3    3   1.0251  11.1930
10  VSURCOND     0    0   2.4502   8.5418

Remove_Unknowns_in_Feature  VTRAFCON [97, 99] 56040  unknown
    feature = 'VTRAFCON'
    A = [
        ['0', [29,40,28,4,98,9,]], #  1.7918 %
        ['1', [0,]], #  62.0091 %
        ['2', [65,2,20,]], #  8.5536 %
        ['3', [3,]], #  25.6994 %
        ['4', [1,7,50,23,8,21,]], #  1.946 %
        ['Unknowns', [97, 99, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

     Feature  Code Name      Per     Corr
0   VTRAFCON    29   29   0.0038  28.0000
1   VTRAFCON    40   40   0.9175  22.5427
2   VTRAFCON    28   28   0.1253  20.6311
3   VTRAFCON     4    4   0.3157  18.5453
4   VTRAFCON    98   98   0.4205  17.2514
5   VTRAFCON     9    9   0.0090  16.9492
6   VTRAFCON     0    0  62.0091  15.9617
7   VTRAFCON    65   65   0.1274  15.8711
8   VTRAFCON     2    2   0.6305  13.9894
9   VTRAFCON    20   20   7.7957  13.6756
10  VTRAFCON     3    3  25.6994  13.6424
11  VTRAFCON     1    1   0.5220  13.4033
12  VTRAFCON     7    7   0.0458  13.2890
13  VTRAFCON    50   50   0.1065  11.0000
14  VTRAFCON    23   23   0.0427  10.6762
15  VTRAFCON     8    8   0.0617  10.5911
16  VTRAFCON    21   21   1.1673   5.7590

Remove_Unknowns_in_Feature  VTRAFWAY [8, 9] 119954  unknown
    feature = 'VTRAFWAY'
    A = [
        ['0', []], #  0.0 %
        ['1', [1,]], #  44.9086 %
        ['2', [5,]], #  5.7073 %
        ['3', [2,]], #  17.2146 %
        ['4', []], #  0.0 %
        ['5', [3,]], #  23.9544 %
        ['6', [6,4,0,]], #  8.2151 %
        ['Unknowns', [8, 9, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name      Per     Corr
0  VTRAFWAY     1    1  44.9086  17.7776
1  VTRAFWAY     5    5   5.7073  14.9798
2  VTRAFWAY     2    2  17.2146  14.9323
3  VTRAFWAY     3    3  23.9544  14.1108
4  VTRAFWAY     6    6   2.7142  11.5876
5  VTRAFWAY     4    4   2.6590  10.8211
6  VTRAFWAY     0    0   2.8419   8.5418

Remove_Unknowns_in_Feature  WEATHER [98, 99] 30047  unknown
    feature = 'WEATHER'
    A = [
        ['0', [5,3,12,6,]], #  0.5666 %
        ['1', [1,]], #  73.5658 %
        ['2', []], #  9.1569 %
        ['3', [2,]], #  0.0 %
        ['4', [10,]], #  15.0742 %
        ['5', [8,11,4,7,]], #  1.6367 %
        ['Unknowns', [98, 99, ]]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name      Per     Corr
0   WEATHER     5    5   0.3586  22.4398
1   WEATHER     3    3   0.1159  17.5505
2   WEATHER    12   12   0.0309  17.5355
3   WEATHER     6    6   0.0612  17.2249
4   WEATHER     1    1  73.5658  15.3569
5   WEATHER     2    2   9.1569  14.9307
6   WEATHER    10   10  15.0742  14.9231
7   WEATHER     8    8   0.0541  14.5946
8   WEATHER    11   11   0.0486  12.3494
9   WEATHER     4    4   1.5173  11.9757
10  WEATHER     7    7   0.0167  11.4035

    feature = 'WRK_ZONE'
    A = [
        ['0', [3,]], #  0.0252 %
        ['1', [0,]], #  98.0404 %
        ['2', [2,1,4,]], #  1.9344 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

    Feature  Code Name      Per     Corr
0  WRK_ZONE     3    3   0.0252  18.3333
1  WRK_ZONE     0    0  98.0404  15.1916
2  WRK_ZONE     2    2   0.1145  14.0759
3  WRK_ZONE     1    1   1.0009  12.0274
4  WRK_ZONE     4    4   0.8190  11.4819

    feature = 'YEAR'
    A = [
        ['0', []], #  0.0 %
        ['1', [2020,]], #  16.8736 %
        ['2', []], #  0.0 %
        ['3', [2021,]], #  17.1339 %
        ['4', []], #  0.0 %
        ['5', [2017,]], #  17.8534 %
        ['6', []], #  0.0 %
        ['7', [2016,]], #  15.209 %
        ['8', []], #  0.0 %
        ['9', [2019,]], #  17.3716 %
        ['10', []], #  0.0 %
        ['11', [2018,]], #  15.5585 %
        ['12', []], #  0.0 %
        ['Unknowns', []]
    ]
    data = Build_Individual_Feature_with_Dict(df_Per, data, feature, A)

  Feature  Code  Name      Per     Corr
0    YEAR  2020  2020  16.8736  16.7586
1    YEAR  2021  2021  17.1339  15.7212
2    YEAR  2017  2017  17.8534  15.2705
3    YEAR  2016  2016  15.2090  14.8269
4    YEAR  2019  2019  17.3716  14.0757
5    YEAR  2018  2018  15.5585  14.0191

       Feature  Code  Name      Per   Corr
0          AGE   106   106   0.0001  100.0
1     BODY_TYP    86    86   0.0003  100.0
2     HOSPITAL     0     0  15.1291  100.0
3     HOSPITAL     1     1  15.1291  100.0
4     MOD_YEAR  1929  1929   0.0001  100.0
...        ...   ...   ...      ...    ...
1306        PJ  4029  4029   0.0006    0.0
1307        PJ  2411  2411   0.0013    0.0
1308        PJ  3209  3209   0.0034    0.0
1309  VE_FORMS    12    12   0.0020    0.0
1310  VE_TOTAL    12    12   0.0020    0.0

[1311 rows x 5 columns]

         Feature  Code  Name      Per      Corr
2       HOSPITAL     0     0  15.1291  100.0000
3       HOSPITAL     1     1  15.1291  100.0000
22         MODEL   709   709   0.5265   65.9303
29      BODY_TYP    80    80   2.3416   62.2476
30          MAKE    72    72   0.9141   62.1368
32         MODEL   706   706   1.4322   61.7808
83      REL_ROAD     4     4   7.4926   35.6646
108         MAKE    98    98   0.6768   32.9325
117     REL_ROAD     3     3   1.4766   31.1023
119     VE_TOTAL     1     1  11.7630   30.9196
139       VALIGN     3     3   3.4009   29.1451
143           PJ  4144  4144   0.6634   28.8973
144          PSU    75    75   1.2499   28.8261
148           PJ  2793  2793   0.5283   28.5676
149     VE_FORMS     1     1  13.7230   28.4193
151      PERMVIT     1     1   8.6581   28.0313
167         HOUR     3     3   0.7306   26.8372
170         HOUR     2     2   0.9483   26.6044
171         HOUR     1     1   1.0665   26.5419
172          PSU    57    57   0.5729   26.4922
184          PSU    40    40   1.5638   25.7640
186           PJ  4147  4147   0.8068   25.6905
189         HOUR     4     4   0.7089   25.6741
212          PSU    52    52   0.9094   24.2102
221           PJ    46    46   0.8138   23.6267
222           PJ   305   305   0.5337   23.6082
231          PSU    64    64   0.8170   23.0875
233         HOUR     0     0   1.3440   23.0705
234          PSU    76    76   0.8271   23.0261
239     VPROFILE     6     6   2.6245   22.9890
243           PJ  1800  1800   1.4170   22.9057
244          PSU    80    80   1.7029   22.8952
246         HOUR    23    23   1.8303   22.8460
247     LGT_COND     2     2   8.1829   22.7854
251     VTRAFCON    40    40   0.9175   22.5427
254          PSU    34    34   0.6524   22.5134
261          PSU    68    68   1.4294   22.2255
267           PJ   295   295   0.5209   22.0608
270     VSPD_LIM    55    55  11.1874   21.7563
273          PSU    66    66   0.6207   21.6302
276       VALIGN     2     2   3.7663   21.4710
279     VPROFILE     5     5   1.9676   21.3597
283         HOUR     5     5   1.1962   21.2548
285           PJ  4135  4135   1.1818   21.2261
299     VPROFILE     3     3   1.2633   20.7547
308           PJ  4152  4152   1.0974   20.4572
310         HOUR    22    22   2.4795   20.4524
318           PJ  1053  1053   2.6320   20.2279
326           PJ   526   526   0.6864   20.0082
345          PSU    50    50   0.5000   19.4507
346      RELJCT2     5     5   0.9431   19.4440
354          PSU    60    60   1.2386   19.2238
355          PSU    24    24   0.6940   19.1842
357     MOD_YEAR  1998  1998   1.1900   19.1381
358     VNUM_LAN     2     2  44.5157   19.1318
359          PSU    63    63   1.9959   19.0844
360          PSU    17    17   3.0890   19.0636
363       REGION     1     1  10.9083   18.9098
368          PSU    55    55   1.0180   18.7775
370      RELJCT2     2     2  28.3024   18.7445
372          PSU    47    47   1.5093   18.7187
373         HOUR    21    21   3.2342   18.7128
379     MOD_YEAR  1996  1996   0.6343   18.5782
384     MOD_YEAR  1997  1997   0.9819   18.4859
385          AGE    71    71   0.5753   18.4667
386          PSU    62    62   1.5962   18.4197
387          PSU    53    53   1.7279   18.3617
388     VSPD_LIM    50    50   3.6373   18.3403
392     MOD_YEAR  2002  2002   2.8112   18.2680
394     DAY_WEEK     1     1  11.3060   18.2198
398           PJ  4150  4150   1.0389   18.0359
399     MOD_YEAR  1995  1995   0.5385   18.0310
401          PSU    10    10   0.5009   18.0190
402           PJ  2670  2670   0.6539   17.9811
403       VALIGN     4     4   1.3458   17.9772
404     VE_TOTAL     5     5   0.7083   17.9660
406          AGE    70    70   0.6013   17.9386
407         HOUR    20    20   3.7818   17.9284
408        MODEL   471   471   0.8945   17.9226
409          AGE    72    72   0.5267   17.9066
411     MOD_YEAR  2001  2001   2.3053   17.8966
414          PSU    49    49   1.0527   17.8781
419     MOD_YEAR  2000  2000   2.0525   17.7990
420     VTRAFWAY     1     1  44.9086   17.7776
421     MOD_YEAR  1999  1999   1.5786   17.7587
422        MODEL   399   399   4.1342   17.7458
424          AGE    57    57   1.1872   17.6832
425     LGT_COND     4     4   1.2618   17.6812
427     VSPD_LIM    70    70   5.2857   17.6610
429        MODEL    22    22   0.7535   17.6306
431          AGE    63    63   0.9184   17.6184
433          AGE    62    62   0.9605   17.5741
434           PJ   206   206   0.6835   17.5723
435          AGE    54    54   1.2411   17.5630
436          PSU    30    30   0.9354   17.5581
440          AGE    66    66   0.7436   17.5115
441         MAKE    22    22   0.8645   17.5091
444     BODY_TYP     8     8   0.5647   17.4416
445          PSU    48    48   2.5464   17.4298
446        MODEL    20    20   0.5622   17.4227
448          AGE    68    68   0.6854   17.3913
449         MAKE    52    52   0.8200   17.3254
451          PSU    82    82   1.0868   17.2921
452        MODEL    50    50   0.9965   17.2550
454     MOD_YEAR  2004  2004   3.7097   17.2414
456         MAKE    14    14   0.5239   17.2254
459          AGE    67    67   0.7175   17.2135
460          AGE    60    60   1.0891   17.2093
461          PSU    35    35   2.6826   17.2030
462         HOUR     6     6   2.4013   17.1788
463          AGE    58    58   1.1608   17.1737
464     MOD_YEAR  2003  2003   3.2958   17.1598
465     MOD_YEAR  2005  2005   4.1720   17.1472
466          AGE    69    69   0.6500   17.1442
467          PSU    31    31   1.5487   17.1297
468          AGE    65    65   0.8130   17.1156
469           PJ   455   455   0.6854   17.1131
477          AGE    61    61   1.0309   16.9967
481           PJ  4153  4153   0.5439   16.9544
483     LGT_COND     3     3  15.6344   16.9451
484          AGE    64    64   0.8589   16.9297
485        MODEL     3     3   0.8121   16.9111
487        MODEL    37    37   3.3066   16.8976
490          AGE    51    51   1.3071   16.8357
491          PSU    25    25   2.6833   16.8329
493     VE_FORMS     5     5   0.6577   16.8123
494          AGE    55    55   1.2657   16.8099
496     DAY_WEEK     7     7  13.8340   16.7877
497         YEAR  2020  2020  16.8736   16.7586
499          SEX     2     2  43.8701   16.7236
501        MODEL    18    18   0.6500   16.7098
502         MAKE    18    18   1.4188   16.6969
503        MODEL    43    43   1.9415   16.6955
511        MODEL     2     2   1.3369   16.6457
512      RELJCT2     1     1  36.8757   16.6403
513        MONTH     7     7   8.5052   16.6255
514          AGE    32    32   1.7949   16.6099
516           PJ  4138  4138   1.0532   16.6068
518         MAKE    37    37   9.3996   16.5811
519          AGE    52    52   1.2748   16.5732
520   URBANICITY     2     2  22.6908   16.5730
521          AGE    56    56   1.2241   16.5652
522          PSU    72    72   1.9925   16.5213
525          PSU    65    65   2.1510   16.4962
528          AGE    59    59   1.1185   16.4646
529      NUMOCCS     2     2  24.9571   16.4544
530        MODEL    17    17   0.6693   16.4363
531     VSPD_LIM    65    65   5.8534   16.4347
532     BODY_TYP     3     3   0.7540   16.4294
533          PSU    56    56   2.2046   16.4135
535          AGE    53    53   1.2330   16.3968
537        MONTH     6     6   8.3279   16.3584
538         MAKE    63    63   3.2402   16.3273
539          AGE    33    33   1.7964   16.3225
541         HOUR    19    19   4.8031   16.2731
542     BODY_TYP     1     1   0.6528   16.2667
543          AGE    35    35   1.7344   16.2529
544        MODEL    36    36   0.5426   16.2448
545     MOD_YEAR  2006  2006   4.4448   16.2405
546          AGE    30    30   1.9953   16.2336
547          AGE    38    38   1.5718   16.2180
548      PERMVIT     8     8   1.4261   16.2146
549           PJ  4141  4141   1.1567   16.2103
551          AGE    29    29   2.1027   16.2049
553           PJ  1723  1723   1.2607   16.1850
554           PJ  4148  4148   1.4999   16.1637
556          AGE    28    28   2.1706   16.1507
557     VE_TOTAL     4     4   2.8370   16.1381
558        MODEL    38    38   0.8563   16.1375
560          AGE    24    24   2.3815   16.1161
561          AGE    40    40   1.4832   16.0924
562     BODY_TYP     2     2   3.0509   16.0850
563          AGE    49    49   1.3503   16.0764
564     MOD_YEAR  2007  2007   4.7809   16.0691
565          PSU    32    32   2.0140   16.0184
566          AGE    27    27   2.2097   16.0138
567          AGE    48    48   1.3305   16.0022
569     BODY_TYP    19    19   0.9264   15.9881
572          AGE    26    26   2.2798   15.9652
574     VTRAFCON     0     0  62.0091   15.9617
575      NUMOCCS     6     6   0.8224   15.9612
577     BODY_TYP     4     4  36.1961   15.9386
578          AGE    41    41   1.4696   15.9367
580         MAKE    35    35   8.1955   15.9056
582        MONTH     8     8   9.1742   15.8942
585      TYP_INT     1     1  57.3325   15.8711
588      PER_TYP     2     2  26.5073   15.8586
591          AGE    22    22   2.5419   15.8314
592          AGE    43    43   1.3761   15.8185
593          PSU    45    45   0.7038   15.8104
594          AGE    31    31   1.9148   15.8030
595          AGE    50    50   1.3247   15.7800
596          AGE    23    23   2.4567   15.7681
597        MODEL    25    25   1.0682   15.7570
598     MOD_YEAR  2020  2020   2.2304   15.7463
599           PJ  4143  4143   0.8483   15.7277
601          AGE    34    34   1.7275   15.7223
602         YEAR  2021  2021  17.1339   15.7212
604          AGE    36    36   1.6587   15.7101
607      TYP_INT     3     3  11.9265   15.7044
608        MONTH     5     5   8.0316   15.7038
610          PSU    83    83   2.3688   15.6836
611         MAKE    55    55   3.9465   15.6813
613          AGE    45    45   1.3841   15.6405
615        MONTH     4     4   7.1594   15.6224
617          AGE    46    46   1.3585   15.6175
618      NUMOCCS     1     1  54.4133   15.6031
619          AGE    47    47   1.3475   15.6015
620          AGE    37    37   1.5851   15.5748
621        MODEL    39    39   0.9467   15.5736
623          PSU    78    78   2.2107   15.5563
624           PJ  2851  2851   0.5318   15.5468
626        MONTH     9     9   9.0999   15.5111
627         MAKE     6     6   1.9862   15.5068
628     LGT_COND     5     5   2.4088   15.5052
629          AGE    25    25   2.3610   15.4982
632          AGE    44    44   1.3716   15.4573
633        MODEL    31    31   2.7365   15.4504
636          AGE    21    21   2.6124   15.4215
637     VSURCOND     1     1  81.8341   15.4078
638     MOD_YEAR  2019  2019   3.7532   15.3988
639      TYP_INT     2     2  29.8771   15.3884
640          AGE    42    42   1.3954   15.3641
641      WEATHER     1     1  73.5658   15.3569
642     VE_TOTAL     3     3  11.5525   15.3563
643        MODEL    32    32   5.3708   15.3559
645        MODEL    47    47   2.7461   15.3304
647     VE_FORMS     4     4   2.6848   15.2991
650          AGE    19    19   2.6797   15.2785
651      BUS_USE     0     0  99.5662   15.2748
653        MODEL    35    35   1.8960   15.2709
654         YEAR  2017  2017  17.8534   15.2705
655           PJ  1482  1482   0.5470   15.2703
656     MOD_YEAR  2009  2009   3.0669   15.2513
658      RELJCT1     0     0  74.3341   15.2418
659     EMER_USE     0     0  99.6821   15.2171
660       REGION     3     3  55.2993   15.1991
661     WRK_ZONE     0     0  98.0404   15.1916
665        MODEL    23    23   1.4285   15.1771
666      SCH_BUS     0     0  99.5024   15.1521
667      INT_HWY     0     0  89.3153   15.1501
668          PSU    67    67   3.8386   15.1473
670   PERNOTMVIT     0     0  99.6555   15.1218
671     LGT_COND     6     6   0.5698   15.1125
672          AGE    20    20   2.6227   15.1111
673      PERMVIT     9     9   0.8072   15.1042
674     VSPD_LIM    45    45  21.9134   15.1027
675          PSU    12    12   3.7949   15.0929
676     PVH_INVL     0     0  97.5149   15.0835
678     VSURCOND     2     2  13.4400   15.0684
679           PJ  2091  2091   0.5164   15.0611
681     VPROFILE     2     2   8.2214   15.0560
684     VPROFILE     1     1  83.0137   15.0114
685          AGE    39    39   1.5288   15.0083
687     VTRAFWAY     5     5   5.7073   14.9798
688     MOD_YEAR  2008  2008   4.4464   14.9776
690      INT_HWY     1     1  10.6847   14.9564
691         MAKE    13    13   0.5809   14.9459
692     VTRAFWAY     2     2  17.2146   14.9323
693      WEATHER     2     2   9.1569   14.9307
694        MODEL    33    33   1.2428   14.9301
695      WEATHER    10    10  15.0742   14.9231
699          PSU    58    58   1.6335   14.8850
700     VE_FORMS     3     3  11.0684   14.8835
702      PER_TYP     1     1  73.4701   14.8639
703     MOD_YEAR  2017  2017   6.8672   14.8623
705         HOUR    10    10   4.0790   14.8444
707         MAKE    20    20  12.6246   14.8349
708      RELJCT1     8     8  21.4580   14.8344
710     BODY_TYP     5     5   2.5745   14.8298
711         YEAR  2016  2016  15.2090   14.8269
713     MOD_YEAR  2018  2018   4.8421   14.8157
714          SEX     1     1  52.3111   14.7688
718      NUMOCCS     3     3  10.4153   14.7541
719        MONTH     3     3   7.5735   14.7533
721     DAY_WEEK     2     2  13.7551   14.7241
723   URBANICITY     1     1  77.3092   14.7053
724      RELJCT1     1     1   4.1716   14.7008
725     MOD_YEAR  2021  2021   0.9773   14.6963
726      NUMOCCS     5     5   2.6919   14.6783
727        MONTH    10    10   9.9153   14.6625
728          PSU    14    14   0.6053   14.6562
731           PJ   456   456   0.5655   14.6468
732        MODEL    34    34   1.5523   14.6430
733     BODY_TYP     9     9   2.8609   14.6233
734           PJ    87    87   1.5738   14.6215
735      PERMVIT     7     7   2.6859   14.6196
736     VSPD_LIM    60    60   2.0159   14.6131
737           PJ  4142  4142   1.9118   14.5946
739           PJ  4145  4145   1.1440   14.5902
740       VALIGN     1     1  88.9692   14.5658
741          PSU    70    70   3.2335   14.5625
742     MOD_YEAR  2016  2016   7.5381   14.5543
743           PJ   457   457   0.5639   14.5378
744          AGE    14    14   0.6049   14.5320
745         MAKE    34    34   1.2997   14.5243
746        MODEL   405   405   0.5617   14.5210
747        MODEL   404   404   2.4258   14.5176
749     DAY_WEEK     4     4  14.6777   14.4718
751     PVH_INVL     1     1   2.0727   14.4422
752     DAY_WEEK     5     5  15.0140   14.4164
753           PJ  4146  4146   1.1734   14.4154
754        MODEL    40    40   3.3504   14.3975
756         HOUR     9     9   3.8258   14.3828
757      PERMVIT     4     4  14.3516   14.3827
758        MODEL    51    51   1.7996   14.3758
759        MONTH     2     2   7.0085   14.3631
760        MONTH     1     1   7.4160   14.3448
761       REGION     2     2  17.8327   14.3436
762          AGE    18    18   2.6914   14.3324
763      PERMVIT     3     3  23.4672   14.3120
772     VNUM_LAN     4     4  14.9317   14.2742
775     DAY_WEEK     3     3  14.3922   14.2369
776     MOD_YEAR  2015  2015   7.4390   14.1867
777         HOUR    14    14   7.0741   14.1841
778     BODY_TYP     6     6   5.2201   14.1666
780     MOD_YEAR  2013  2013   5.7901   14.1389
783        MODEL   401   401   4.2732   14.1283
784         HOUR    11    11   5.0904   14.1232
786     VTRAFWAY     3     3  23.9544   14.1108
787         MAKE    49    49  11.6921   14.1030
789        MONTH    11    11   8.9901   14.0935
792         YEAR  2019  2019  17.3716   14.0757
793     MOD_YEAR  2014  2014   6.3318   14.0579
794         HOUR    18    18   7.0147   14.0458
795      PERMVIT     5     5   9.0994   14.0444
797          AGE    15    15   0.8040   14.0289
798         HOUR    13    13   6.2852   14.0212
799         YEAR  2018  2018  15.5585   14.0191
800     DAY_WEEK     6     6  17.0209   14.0052
801           PJ  2810  2810   0.7122   13.9906
802     VTRAFCON     2     2   0.6305   13.9894
803      PERMVIT     6     6   5.1931   13.9869
806      NUMOCCS     4     4   5.9609   13.9214
807          AGE    10    10   0.5428   13.9171
809     VSPD_LIM    40    40  11.3393   13.8911
811     LGT_COND     1     1  71.9161   13.8767
812           PJ   516   516   0.6682   13.8423
814     VNUM_LAN     3     3  18.4957   13.8262
815     BODY_TYP    14    14  16.1724   13.8230
818          AGE     8     8   0.5325   13.7661
819     VSPD_LIM    35    35  18.9864   13.7623
821         MAKE    12    12  13.2670   13.7506
823     VNUM_LAN     5     5  11.2134   13.7448
824         MAKE    19    19   0.9039   13.7441
827         MAKE    41    41   1.4753   13.7050
829     VTRAFCON    20    20   7.7957   13.6756
830        MODEL   402   402   5.0728   13.6499
831        MODEL   499   499   2.1336   13.6486
832     VSURCOND     4     4   0.7920   13.6439
833     VTRAFCON     3     3  25.6994   13.6424
834         MAKE    30    30   1.5380   13.6385
836         MAKE    58    58   0.8873   13.6144
838          AGE    13    13   0.5189   13.5802
839        MONTH    12    12   8.7985   13.5785
842          AGE    17    17   2.2366   13.5492
843        MODEL    46    46   0.9659   13.5229
844           PJ  4139  4139   1.7672   13.5052
845         HOUR    12    12   6.2797   13.4761
848          PSU    28    28   3.1903   13.4680
849        MODEL    24    24   1.1988   13.4557
850        MODEL    42    42   0.6077   13.4456
851        MODEL   442   442   1.6318   13.4146
852           PJ  1919  1919   1.7813   13.4057
853     VTRAFCON     1     1   0.5220   13.4033
856         HOUR     8     8   4.5183   13.3792
857     MOD_YEAR  2012  2012   4.9401   13.3701
858          PSU    33    33   3.1837   13.3595
860         HOUR    16    16   8.6935   13.3526
861         MAKE     2     2   3.2763   13.3406
863     MOD_YEAR  2011  2011   3.9647   13.3057
866     MOD_YEAR  2010  2010   3.5628   13.2662
869         MAKE    42    42   1.3235   13.2269
872       REGION     4     4  15.9597   13.1802
873         HOUR     7     7   4.6948   13.1665
874      PERMVIT     2     2  33.1765   13.1615
876         MAKE    54    54   0.9853   13.1449
878           PJ  2907  2907   0.5421   13.1075
880         MAKE     7     7   5.9167   13.0563
882     REL_ROAD     1     1  88.4404   13.0393
884          AGE     7     7   0.5389   13.0218
887          AGE     9     9   0.5362   12.9758
891         HOUR    15    15   8.6077   12.9617
896      RELJCT2     8     8   7.4513   12.9268
897          AGE    11    11   0.5152   12.9265
899     BODY_TYP    20    20   4.1037   12.9021
905          PSU    13    13   0.7171   12.8005
909          PSU    77    77   1.0387   12.7091
914         HOUR    17    17   9.3121   12.6166
916     VNUM_LAN     7     7   1.4350   12.5936
917     VE_FORMS     2     2  71.5442   12.5767
919        MODEL   403   403   2.5595   12.5493
920          AGE    12    12   0.5192   12.5395
922          AGE    16    16   1.6727   12.4521
923     VE_TOTAL     2     2  72.7797   12.4410
924           PJ  4140  4140   0.6654   12.4052
925         MAKE    23    23   2.6606   12.3866
926         MAKE    59    59   1.4172   12.3728
932          AGE     6     6   0.5337   12.2836
936     VSPD_LIM    25    25   8.5860   12.2317
938        MODEL   441   441   1.7103   12.2009
939        MODEL   472   472   1.2857   12.1975
941          PSU    20    20   1.2642   12.1494
944           PJ  1484  1484   1.5282   12.1229